// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Io {
	public class Path : global::Loreline.Internal.Lang.HxObject {
		
		public Path(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public Path(string path) {
			global::Loreline.Internal.Io.Path.__hx_ctor_haxe_io_Path(this, path);
		}
		
		
		protected static void __hx_ctor_haxe_io_Path(global::Loreline.Internal.Io.Path __hx_this, string path) {
			unchecked {
				switch (path) {
					case ".":
					case "..":
					{
						__hx_this.dir = path;
						__hx_this.file = "";
						return;
					}
					
					
				}
				
				int c1 = global::Loreline.Internal.Lang.StringExt.lastIndexOf(path, "/", default(global::Loreline.Internal.Lang.Null<int>));
				int c2 = global::Loreline.Internal.Lang.StringExt.lastIndexOf(path, "\\", default(global::Loreline.Internal.Lang.Null<int>));
				if (( c1 < c2 )) {
					__hx_this.dir = global::Loreline.Internal.Lang.StringExt.substr(path, 0, new global::Loreline.Internal.Lang.Null<int>(c2, true));
					path = global::Loreline.Internal.Lang.StringExt.substr(path, ( c2 + 1 ), default(global::Loreline.Internal.Lang.Null<int>));
					__hx_this.backslash = true;
				}
				else if (( c2 < c1 )) {
					__hx_this.dir = global::Loreline.Internal.Lang.StringExt.substr(path, 0, new global::Loreline.Internal.Lang.Null<int>(c1, true));
					path = global::Loreline.Internal.Lang.StringExt.substr(path, ( c1 + 1 ), default(global::Loreline.Internal.Lang.Null<int>));
				}
				else {
					__hx_this.dir = null;
				}
				
				int cp = global::Loreline.Internal.Lang.StringExt.lastIndexOf(path, ".", default(global::Loreline.Internal.Lang.Null<int>));
				if (( cp != -1 )) {
					__hx_this.ext = global::Loreline.Internal.Lang.StringExt.substr(path, ( cp + 1 ), default(global::Loreline.Internal.Lang.Null<int>));
					__hx_this.file = global::Loreline.Internal.Lang.StringExt.substr(path, 0, new global::Loreline.Internal.Lang.Null<int>(cp, true));
				}
				else {
					__hx_this.ext = null;
					__hx_this.file = path;
				}
				
			}
		}
		
		
		public static string directory(string path) {
			global::Loreline.Internal.Io.Path s = new global::Loreline.Internal.Io.Path(((string) (path) ));
			if (( s.dir == null )) {
				return "";
			}
			
			return s.dir;
		}
		
		
		public static string @join(global::Loreline.Internal.Root.Array<string> paths) {
			unchecked {
				global::Loreline.Internal.Root.Array<string> ret = new global::Loreline.Internal.Root.Array<string>(new string[]{});
				{
					int _g = 0;
					int _g1 = paths.length;
					while (( _g < _g1 )) {
						int i = _g++;
						string elt = ((string) (paths.__a[i]) );
						if (( ( elt != null ) && ( elt != "" ) )) {
							ret.push(elt);
						}
						
					}
					
				}
				
				global::Loreline.Internal.Root.Array<string> paths1 = ret;
				if (( paths1.length == 0 )) {
					return "";
				}
				
				string path = paths1[0];
				{
					int _g2 = 1;
					int _g3 = paths1.length;
					while (( _g2 < _g3 )) {
						int i1 = _g2++;
						path = global::Loreline.Internal.Io.Path.addTrailingSlash(path);
						path = global::Loreline.Internal.Lang.Runtime.concat(path, paths1[i1]);
					}
					
				}
				
				return global::Loreline.Internal.Io.Path.normalize(path);
			}
		}
		
		
		public static string normalize(string path) {
			unchecked {
				string slash = "/";
				path = global::Loreline.Internal.Lang.StringExt.split(path, "\\").@join(slash);
				if (( path == slash )) {
					return slash;
				}
				
				global::Loreline.Internal.Root.Array<string> target = new global::Loreline.Internal.Root.Array<string>(new string[]{});
				{
					int _g = 0;
					global::Loreline.Internal.Root.Array<string> _g1 = global::Loreline.Internal.Lang.StringExt.split(path, slash);
					while (( _g < _g1.length )) {
						string token = _g1[_g];
						 ++ _g;
						if (( ( ( token == ".." ) && ( target.length > 0 ) ) && ( target[( target.length - 1 )] != ".." ) )) {
							string __temp_expr1 = global::Loreline.Internal.Lang.Runtime.toString((target.pop()).toDynamic());
						}
						else if (( token == "" )) {
							if (( ( target.length > 0 ) || global::Loreline.Internal.Lang.Runtime.eq((global::Loreline.Internal.Lang.StringExt.charCodeAt(path, 0)).toDynamic(), 47) )) {
								target.push(token);
							}
							
						}
						else if (( token != "." )) {
							target.push(token);
						}
						
					}
					
				}
				
				string tmp = target.@join(slash);
				global::Loreline.Internal.Root.StringBuf acc = new global::Loreline.Internal.Root.StringBuf();
				bool colon = false;
				bool slashes = false;
				{
					int _g_offset = 0;
					string _g_s = tmp;
					while (( _g_offset < _g_s.Length )) {
						string s = _g_s;
						int index = _g_offset++;
						int c = ( (( ((uint) (index) ) < s.Length )) ? (((int) (s[index]) )) : (-1) );
						if (( ( c >= 55296 ) && ( c <= 56319 ) )) {
							int index1 = ( index + 1 );
							c = ( ( ( c - 55232 ) << 10 ) | ( (( (( ((uint) (index1) ) < s.Length )) ? (((int) (s[index1]) )) : (-1) )) & 1023 ) );
						}
						
						int c1 = c;
						if (( c1 >= 65536 )) {
							 ++ _g_offset;
						}
						
						int c2 = c1;
						switch (c2) {
							case 47:
							{
								if ( ! (colon) ) {
									slashes = true;
								}
								else {
									int i = c2;
									{
										colon = false;
										if (slashes) {
											acc.b.Append(((string) ("/") ));
											slashes = false;
										}
										
										acc.addChar(i);
									}
									
								}
								
								break;
							}
							
							
							case 58:
							{
								acc.b.Append(((string) (":") ));
								colon = true;
								break;
							}
							
							
							default:
							{
								int i1 = c2;
								{
									colon = false;
									if (slashes) {
										acc.b.Append(((string) ("/") ));
										slashes = false;
									}
									
									acc.addChar(i1);
								}
								
								break;
							}
							
						}
						
					}
					
				}
				
				return acc.b.ToString();
			}
		}
		
		
		public static string addTrailingSlash(string path) {
			unchecked {
				if (( path.Length == 0 )) {
					return "/";
				}
				
				int c1 = global::Loreline.Internal.Lang.StringExt.lastIndexOf(path, "/", default(global::Loreline.Internal.Lang.Null<int>));
				int c2 = global::Loreline.Internal.Lang.StringExt.lastIndexOf(path, "\\", default(global::Loreline.Internal.Lang.Null<int>));
				if (( c1 < c2 )) {
					if (( c2 != ( path.Length - 1 ) )) {
						return global::Loreline.Internal.Lang.Runtime.concat(path, "\\");
					}
					else {
						return path;
					}
					
				}
				else if (( c1 != ( path.Length - 1 ) )) {
					return global::Loreline.Internal.Lang.Runtime.concat(path, "/");
				}
				else {
					return path;
				}
				
			}
		}
		
		
		public static bool isAbsolute(string path) {
			unchecked {
				if (path.StartsWith("/")) {
					return true;
				}
				
				if (( global::Loreline.Internal.Lang.StringExt.charAt(path, 1) == ":" )) {
					return true;
				}
				
				if (path.StartsWith("\\\\")) {
					return true;
				}
				
				return false;
			}
		}
		
		
		public string dir;
		
		public string file;
		
		public string ext;
		
		public bool backslash;
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1212528822:
					{
						this.backslash = global::Loreline.Internal.Lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					case 5049505:
					{
						this.ext = global::Loreline.Internal.Lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 1136381564:
					{
						this.file = global::Loreline.Internal.Lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 4996429:
					{
						this.dir = global::Loreline.Internal.Lang.Runtime.toString(@value);
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1212528822:
					{
						return this.backslash;
					}
					
					
					case 5049505:
					{
						return this.ext;
					}
					
					
					case 1136381564:
					{
						return this.file;
					}
					
					
					case 4996429:
					{
						return this.dir;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("backslash");
			baseArr.push("ext");
			baseArr.push("file");
			baseArr.push("dir");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


