#!/usr/bin/env node

import { spawn } from 'node:child_process';
import * as url from 'node:url';
const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

async function command(command, args = []) {
    const childProcess = spawn(command, args, {
        stdio: 'inherit'
    });

    return new Promise((resolve, reject) => {
        childProcess.on('error', reject);
        childProcess.on('close', (code) => {
            if (code === 0) resolve();
            else reject(new Error(`Command failed with code ${code}`));
        });
    });
}

// Example usage with async/await
async function main() {

    process.chdir(__dirname);
    let rawArgs = process.argv.slice(2);

    let haxeBuildArgs = ['build-cli.hxml'];
    let lorelineArgs = [];

    let i = 0;
    while (i < rawArgs.length) {
        if (rawArgs[i].startsWith('-D')) {
            haxeBuildArgs.push('-D');
            haxeBuildArgs.push(rawArgs[i].substring(2));
        }
        else if (rawArgs[i] == '--debug') {
            haxeBuildArgs.push('--debug');
        }
        else {
            lorelineArgs.push(rawArgs[i]);
        }
        i++;
    }

    await command('haxe', ['--neko', 'run.n'].concat(haxeBuildArgs));
    await command('neko', ['run.n'].concat(lorelineArgs).concat([__dirname]));

}

(async () => {
    try {
        await main();
    } catch (error) {
        console.error(error);
    }
})();
