// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060
namespace Loreline.Runtime {
	public class Error : global::Loreline.Internal.Lang.HxObject {
		
		public Error(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public Error(string message, global::Loreline.Runtime.Position pos) {
			global::Loreline.Runtime.Error.__hx_ctor_loreline_Error(this, message, pos);
		}
		
		
		protected static void __hx_ctor_loreline_Error(global::Loreline.Runtime.Error __hx_this, string message, global::Loreline.Runtime.Position pos) {
			__hx_this.message = message;
			__hx_this.pos = pos;
			__hx_this.stack = global::Loreline.Internal._CallStack.CallStack_Impl_.callStack();
		}
		
		
		public string message;
		
		public global::Loreline.Runtime.Position pos;
		
		public global::Loreline.Internal.Root.Array<object> stack;
		
		public virtual string toString() {
			return global::Loreline.Internal.Lang.Runtime.concat(global::Loreline.Internal.Lang.Runtime.concat(global::Loreline.Internal.Lang.Runtime.concat("", this.message), " at "), this.pos.toString());
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 67856200:
					{
						this.stack = ((global::Loreline.Internal.Root.Array<object>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<object>(((global::Loreline.Internal.Root.Array) (@value) ))) );
						return @value;
					}
					
					
					case 5594516:
					{
						this.pos = ((global::Loreline.Runtime.Position) (@value) );
						return @value;
					}
					
					
					case 437335495:
					{
						this.message = global::Loreline.Internal.Lang.Runtime.toString(@value);
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 946786476:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 67856200:
					{
						return this.stack;
					}
					
					
					case 5594516:
					{
						return this.pos;
					}
					
					
					case 437335495:
					{
						return this.message;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 946786476:
					{
						return this.toString();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("stack");
			baseArr.push("pos");
			baseArr.push("message");
			base.__hx_getFields(baseArr);
		}
		
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}


