// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Runtime._Imports {
	public class ImportsLoopInfo : global::Loreline.Internal.Lang.HxObject {
		
		public ImportsLoopInfo(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public ImportsLoopInfo(bool finished) {
			global::Loreline.Runtime._Imports.ImportsLoopInfo.__hx_ctor_loreline__Imports_ImportsLoopInfo(this, finished);
		}
		
		
		protected static void __hx_ctor_loreline__Imports_ImportsLoopInfo(global::Loreline.Runtime._Imports.ImportsLoopInfo __hx_this, bool finished) {
			__hx_this.finished = finished;
		}
		
		
		public bool finished;
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 353276786:
					{
						this.finished = global::Loreline.Internal.Lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 353276786:
					{
						return this.finished;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("finished");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Runtime {
	public class Imports : global::Loreline.Internal.Lang.HxObject {
		
		public Imports(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public Imports() {
			global::Loreline.Runtime.Imports.__hx_ctor_loreline_Imports(this);
		}
		
		
		protected static void __hx_ctor_loreline_Imports(global::Loreline.Runtime.Imports __hx_this) {
			__hx_this.ext = ".lor";
			__hx_this.pendingImports = 0;
			__hx_this.hasErrors = false;
			__hx_this.done = null;
			__hx_this.resolvedImports = null;
			__hx_this.autoAddExtension = true;
			{
			}
			
		}
		
		
		public global::Loreline.Internal.Lang.Function handleFile;
		
		public global::Loreline.Internal.Lang.Function handleError;
		
		public global::Loreline.Internal.Root.Array<object> tokens;
		
		public string rootPath;
		
		public bool autoAddExtension;
		
		public global::Loreline.Internal.Ds.StringMap<object> resolvedImports;
		
		public global::Loreline.Internal.Lang.Function done;
		
		public bool hasErrors;
		
		public int pendingImports;
		
		public string ext;
		
		public virtual void resolve(string rootPath, global::Loreline.Internal.Root.Array<object> tokens, global::Loreline.Internal.Lang.Function handleFile, global::Loreline.Internal.Lang.Function handleError, global::Loreline.Internal.Lang.Function done) {
			this.rootPath = rootPath;
			this.tokens = tokens;
			this.handleFile = handleFile;
			this.handleError = handleError;
			this.done = done;
			this.hasErrors = false;
			this.pendingImports = 0;
			if (( ( rootPath != null ) && rootPath.EndsWith(".lor.txt") )) {
				this.ext = ".lor.txt";
			}
			
			global::Loreline.Internal.Ds.StringMap<object> resolvedImports = new global::Loreline.Internal.Ds.StringMap<object>();
			global::Loreline.Internal.Root.Array<string> toImport = new global::Loreline.Internal.Root.Array<string>(new string[]{});
			global::Loreline.Internal.Ds.StringMap<bool> visitedImports = new global::Loreline.Internal.Ds.StringMap<bool>();
			string cwd = global::Loreline.Internal.Io.Path.directory(rootPath);
			this.extractImports(cwd, tokens, toImport, visitedImports);
			this.processImports(toImport, visitedImports, resolvedImports);
		}
		
		
		public virtual void processImports(global::Loreline.Internal.Root.Array<string> toImport, global::Loreline.Internal.Ds.StringMap<bool> visitedImports, global::Loreline.Internal.Ds.StringMap<object> resolvedImports) {
			global::Loreline.Runtime._Imports.ImportsLoopInfo loopInfo = new global::Loreline.Runtime._Imports.ImportsLoopInfo(((bool) (false) ));
			while (( toImport.length > 0 )) {
				string item = global::Loreline.Internal.Lang.Runtime.toString((toImport.shift()).toDynamic());
				this.handleItemInLoop(item, loopInfo, toImport, visitedImports, resolvedImports);
			}
			
			loopInfo.finished = true;
			if (( ( this.pendingImports == 0 ) && ( this.done != null ) )) {
				this.resolvedImports = resolvedImports;
				this.done.__hx_invoke2_o(default(double), this.hasErrors, default(double), resolvedImports);
				this.done = null;
			}
			
		}
		
		
		public virtual void handleItemInLoop(string item, global::Loreline.Runtime._Imports.ImportsLoopInfo loopInfo, global::Loreline.Internal.Root.Array<string> toImport, global::Loreline.Internal.Ds.StringMap<bool> visitedImports, global::Loreline.Internal.Ds.StringMap<object> resolvedImports) {
			global::Loreline.Runtime.Imports _gthis = this;
			this.handleFile.__hx_invoke2_o(default(double), item, default(double), new global::Loreline.Runtime.Imports_handleItemInLoop_92__Fun(visitedImports, toImport, resolvedImports, loopInfo, item, _gthis));
		}
		
		
		public virtual void extractImports(string cwd, global::Loreline.Internal.Root.Array<object> tokens, global::Loreline.Internal.Root.Array<string> toImport, global::Loreline.Internal.Ds.StringMap<bool> visitedImports) {
			unchecked {
				int i = 0;
				int len = tokens.length;
				while (( i < ( len - 1 ) )) {
					if (( ((global::Loreline.Runtime.Token) (tokens[i]) ).type == global::Loreline.Runtime.TokenType.KwImport )) {
						global::Loreline.Runtime.TokenType _g = ((global::Loreline.Runtime.Token) (tokens[( i + 1 )]) ).type;
						if (( _g._hx_index == 9 )) {
							int _g1 = ( _g as global::Loreline.Runtime.TokenType_LString ).quotes;
							global::Loreline.Internal.Root.Array<object> _g2 = ( _g as global::Loreline.Runtime.TokenType_LString ).attachments;
							{
								string s = ( _g as global::Loreline.Runtime.TokenType_LString ).s;
								{
									string path = s;
									if ( ! (global::Loreline.Internal.Io.Path.isAbsolute(s)) ) {
										path = global::Loreline.Internal.Io.Path.@join(new global::Loreline.Internal.Root.Array<string>(new string[]{cwd, path}));
									}
									
									path = global::Loreline.Internal.Io.Path.normalize(path);
									if ( ! (path.ToLowerInvariant().EndsWith(this.ext)) ) {
										path = global::Loreline.Internal.Lang.Runtime.concat(path, this.ext);
									}
									
									if ( ! (visitedImports.exists(path)) ) {
										this.pendingImports++;
										visitedImports.@set(path, true);
										toImport.push(path);
									}
									
								}
								
							}
							
						}
						
					}
					
					 ++ i;
				}
				
			}
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 77000663:
					{
						this.pendingImports = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 5049505:
					{
						this.ext = global::Loreline.Internal.Lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 77000663:
					{
						this.pendingImports = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 307312293:
					{
						this.hasErrors = global::Loreline.Internal.Lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					case 1114501250:
					{
						this.done = ((global::Loreline.Internal.Lang.Function) (@value) );
						return @value;
					}
					
					
					case 1176449622:
					{
						this.resolvedImports = ((global::Loreline.Internal.Ds.StringMap<object>) (global::Loreline.Internal.Ds.StringMap<object>.__hx_cast<object>(((global::Loreline.Internal.Ds.StringMap) (@value) ))) );
						return @value;
					}
					
					
					case 834063149:
					{
						this.autoAddExtension = global::Loreline.Internal.Lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					case 1636350183:
					{
						this.rootPath = global::Loreline.Internal.Lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 300357466:
					{
						this.tokens = ((global::Loreline.Internal.Root.Array<object>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<object>(((global::Loreline.Internal.Root.Array) (@value) ))) );
						return @value;
					}
					
					
					case 628324096:
					{
						this.handleError = ((global::Loreline.Internal.Lang.Function) (@value) );
						return @value;
					}
					
					
					case 1650553412:
					{
						this.handleFile = ((global::Loreline.Internal.Lang.Function) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1072735277:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "extractImports", 1072735277)) );
					}
					
					
					case 1106376740:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "handleItemInLoop", 1106376740)) );
					}
					
					
					case 472438975:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "processImports", 472438975)) );
					}
					
					
					case 1734349548:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "resolve", 1734349548)) );
					}
					
					
					case 5049505:
					{
						return this.ext;
					}
					
					
					case 77000663:
					{
						return this.pendingImports;
					}
					
					
					case 307312293:
					{
						return this.hasErrors;
					}
					
					
					case 1114501250:
					{
						return this.done;
					}
					
					
					case 1176449622:
					{
						return this.resolvedImports;
					}
					
					
					case 834063149:
					{
						return this.autoAddExtension;
					}
					
					
					case 1636350183:
					{
						return this.rootPath;
					}
					
					
					case 300357466:
					{
						return this.tokens;
					}
					
					
					case 628324096:
					{
						return this.handleError;
					}
					
					
					case 1650553412:
					{
						return this.handleFile;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 77000663:
					{
						return ((double) (this.pendingImports) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 1072735277:
					{
						this.extractImports(global::Loreline.Internal.Lang.Runtime.toString(dynargs[0]), ((global::Loreline.Internal.Root.Array<object>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<object>(((global::Loreline.Internal.Root.Array) (dynargs[1]) ))) ), ((global::Loreline.Internal.Root.Array<string>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<string>(((global::Loreline.Internal.Root.Array) (dynargs[2]) ))) ), ((global::Loreline.Internal.Ds.StringMap<bool>) (global::Loreline.Internal.Ds.StringMap<object>.__hx_cast<bool>(((global::Loreline.Internal.Ds.StringMap) (dynargs[3]) ))) ));
						break;
					}
					
					
					case 1106376740:
					{
						this.handleItemInLoop(global::Loreline.Internal.Lang.Runtime.toString(dynargs[0]), ((global::Loreline.Runtime._Imports.ImportsLoopInfo) (dynargs[1]) ), ((global::Loreline.Internal.Root.Array<string>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<string>(((global::Loreline.Internal.Root.Array) (dynargs[2]) ))) ), ((global::Loreline.Internal.Ds.StringMap<bool>) (global::Loreline.Internal.Ds.StringMap<object>.__hx_cast<bool>(((global::Loreline.Internal.Ds.StringMap) (dynargs[3]) ))) ), ((global::Loreline.Internal.Ds.StringMap<object>) (global::Loreline.Internal.Ds.StringMap<object>.__hx_cast<object>(((global::Loreline.Internal.Ds.StringMap) (dynargs[4]) ))) ));
						break;
					}
					
					
					case 472438975:
					{
						this.processImports(((global::Loreline.Internal.Root.Array<string>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<string>(((global::Loreline.Internal.Root.Array) (dynargs[0]) ))) ), ((global::Loreline.Internal.Ds.StringMap<bool>) (global::Loreline.Internal.Ds.StringMap<object>.__hx_cast<bool>(((global::Loreline.Internal.Ds.StringMap) (dynargs[1]) ))) ), ((global::Loreline.Internal.Ds.StringMap<object>) (global::Loreline.Internal.Ds.StringMap<object>.__hx_cast<object>(((global::Loreline.Internal.Ds.StringMap) (dynargs[2]) ))) ));
						break;
					}
					
					
					case 1734349548:
					{
						this.resolve(global::Loreline.Internal.Lang.Runtime.toString(dynargs[0]), ((global::Loreline.Internal.Root.Array<object>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<object>(((global::Loreline.Internal.Root.Array) (dynargs[1]) ))) ), ((global::Loreline.Internal.Lang.Function) (dynargs[2]) ), ((global::Loreline.Internal.Lang.Function) (dynargs[3]) ), ((global::Loreline.Internal.Lang.Function) (dynargs[4]) ));
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("ext");
			baseArr.push("pendingImports");
			baseArr.push("hasErrors");
			baseArr.push("done");
			baseArr.push("resolvedImports");
			baseArr.push("autoAddExtension");
			baseArr.push("rootPath");
			baseArr.push("tokens");
			baseArr.push("handleError");
			baseArr.push("handleFile");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Runtime {
	public class Imports_handleItemInLoop_92__Fun : global::Loreline.Internal.Lang.Function {
		
		public Imports_handleItemInLoop_92__Fun(global::Loreline.Internal.Ds.StringMap<bool> visitedImports, global::Loreline.Internal.Root.Array<string> toImport, global::Loreline.Internal.Ds.StringMap<object> resolvedImports, global::Loreline.Runtime._Imports.ImportsLoopInfo loopInfo, string item, global::Loreline.Runtime.Imports _gthis) : base(1, 0) {
			this.visitedImports = visitedImports;
			this.toImport = toImport;
			this.resolvedImports = resolvedImports;
			this.loopInfo = loopInfo;
			this.item = item;
			this._gthis = _gthis;
		}
		
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			string data = ( (( __fn_dyn1 == global::Loreline.Internal.Lang.Runtime.undefined )) ? (global::Loreline.Internal.Lang.Runtime.toString(__fn_float1)) : (global::Loreline.Internal.Lang.Runtime.toString(__fn_dyn1)) );
			this._gthis.pendingImports--;
			if (( data != null )) {
				try {
					global::Loreline.Runtime.Lexer lexer = new global::Loreline.Runtime.Lexer(((string) (data) ));
					global::Loreline.Internal.Root.Array<object> tokens = lexer.tokenize();
					global::Loreline.Internal.Root.Array<object> lexerErrors = lexer.getErrors();
					if (( ( lexerErrors != null ) && ( lexerErrors.length > 0 ) )) {
						this._gthis.handleError.__hx_invoke1_o(default(double), ((global::Loreline.Runtime.LexerError) (lexerErrors[0]) ));
					}
					
					this.resolvedImports.@set(this.item, tokens);
					this._gthis.extractImports(global::Loreline.Internal.Io.Path.directory(this.item), tokens, this.toImport, this.visitedImports);
					if (this.loopInfo.finished) {
						this._gthis.processImports(this.toImport, this.visitedImports, this.resolvedImports);
					}
					
				}
				catch (global::System.Exception _g){
					object e = ((object) (global::Loreline.Internal.Exception.caught(_g).unwrap()) );
					{
						this._gthis.hasErrors = true;
						if (( e is global::Loreline.Runtime.Error )) {
							this._gthis.handleError.__hx_invoke1_o(default(double), ((global::Loreline.Runtime.Error) (((object) (e) )) ));
						}
						else {
							throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(e)) );
						}
						
					}
					
				}
				
				
			}
			else {
				this._gthis.hasErrors = true;
			}
			
			if (( ( this.loopInfo.finished && ( this._gthis.pendingImports == 0 ) ) && ( this._gthis.done != null ) )) {
				this._gthis.resolvedImports = this.resolvedImports;
				this._gthis.done.__hx_invoke2_o(default(double), this._gthis.hasErrors, default(double), this.resolvedImports);
				this._gthis.done = null;
			}
			
			return null;
		}
		
		
		public global::Loreline.Internal.Ds.StringMap<bool> visitedImports;
		
		public global::Loreline.Internal.Root.Array<string> toImport;
		
		public global::Loreline.Internal.Ds.StringMap<object> resolvedImports;
		
		public global::Loreline.Runtime._Imports.ImportsLoopInfo loopInfo;
		
		public string item;
		
		public global::Loreline.Runtime.Imports _gthis;
		
	}
}


