// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Runtime {
	public class Random : global::Loreline.Internal.Lang.HxObject {
		
		public Random(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public Random(object seed) {
			global::Loreline.Runtime.Random.__hx_ctor_loreline_Random(this, seed);
		}
		
		
		protected static void __hx_ctor_loreline_Random(global::Loreline.Runtime.Random __hx_this, object seed) {
			unchecked {
				double seed1 = ( (( seed == default(object) )) ? (((double) (-1) )) : (((double) (global::Loreline.Internal.Lang.Runtime.toDouble(seed)) )) );
				if (( seed1 < 0 )) {
					double now = global::Loreline.Internal.Root.Sys.time();
					seed1 = ( now * 1000000 );
					seed1 += ( global::Loreline.Internal.Root.Math.rand.NextDouble() * 100000 );
					seed1 += ( ( ((double) (global::System.Environment.TickCount) ) / 1000 ) * 10000 );
					seed1 %= ((double) (2147483647) );
				}
				
				__hx_this.seed = seed1;
				__hx_this.initialSeed = __hx_this.seed;
			}
		}
		
		
		public double seed;
		
		public double initialSeed;
		
		public double next() {
			unchecked {
				return ( ( (this.seed = ( ( this.seed * 16807 ) % 2147483647 )) / 2147483647 ) + 0.000000000233 );
			}
		}
		
		
		public int between(int min, int max) {
			unchecked {
				return ((int) (global::System.Math.Floor(((double) (( min + ( (( max - min )) * (( ( (this.seed = ( ( this.seed * 16807 ) % 2147483647 )) / 2147483647 ) + 0.000000000233 )) ) )) ))) );
			}
		}
		
		
		public void reset(object initialSeed) {
			if (( initialSeed != default(object) )) {
				this.initialSeed = ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(initialSeed)) );
			}
			
			this.seed = this.initialSeed;
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 678777877:
					{
						this.initialSeed = ((double) (@value) );
						return @value;
					}
					
					
					case 1280345457:
					{
						this.seed = ((double) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 678777877:
					{
						this.initialSeed = ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					case 1280345457:
					{
						this.seed = ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1724402127:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "reset", 1724402127)) );
					}
					
					
					case 1723044296:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "between", 1723044296)) );
					}
					
					
					case 1224901875:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "next", 1224901875)) );
					}
					
					
					case 678777877:
					{
						return this.initialSeed;
					}
					
					
					case 1280345457:
					{
						return this.seed;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 678777877:
					{
						return this.initialSeed;
					}
					
					
					case 1280345457:
					{
						return this.seed;
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 1724402127:
					{
						this.reset(( (( dynargs.Length > 0 )) ? (((object) (dynargs[0]) )) : (null) ));
						break;
					}
					
					
					case 1723044296:
					{
						return this.between(((int) (global::Loreline.Internal.Lang.Runtime.toInt(((object) (dynargs[0]) ))) ), ((int) (global::Loreline.Internal.Lang.Runtime.toInt(((object) (dynargs[1]) ))) ));
					}
					
					
					case 1224901875:
					{
						return this.next();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array baseArr) {
			baseArr.push("initialSeed");
			baseArr.push("seed");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


