// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Runtime {
	public class Script : global::Loreline.Runtime.Node {
		
		public Script(global::Loreline.Internal.Lang.EmptyObject empty) : base(global::Loreline.Internal.Lang.EmptyObject.EMPTY) {
		}
		
		
		public Script(long id, global::Loreline.Runtime.Position pos, global::Loreline.Internal.Root.Array<object> body) : base(global::Loreline.Internal.Lang.EmptyObject.EMPTY) {
			global::Loreline.Runtime.Script.__hx_ctor_loreline_Script(this, id, pos, body);
		}
		
		
		protected static void __hx_ctor_loreline_Script(global::Loreline.Runtime.Script __hx_this, long id, global::Loreline.Runtime.Position pos, global::Loreline.Internal.Root.Array<object> body) {
			global::Loreline.Runtime.Node.__hx_ctor_loreline_Node(__hx_this, id, pos);
			__hx_this.body = body;
		}
		
		
		public global::Loreline.Internal.Root.Array<object> body;
		
		public override object toJson() {
			object json = base.toJson();
			global::Loreline.Internal.Root.Array _g = new global::Loreline.Internal.Root.Array<object>(new object[]{});
			{
				int _g1 = 0;
				global::Loreline.Internal.Root.Array<object> _g2 = this.body;
				while (( _g1 < _g2.length )) {
					global::Loreline.Runtime.AstNode decl = ((global::Loreline.Runtime.AstNode) (_g2[_g1]) );
					 ++ _g1;
					int __temp_expr1 = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(global::Loreline.Internal.Lang.Runtime.callField(_g, "push", 1247875546, new object[]{decl.toJson()}))) );
				}
				
			}
			
			global::Loreline.Internal.Root.Array __temp_expr2 = ((global::Loreline.Internal.Root.Array) (global::Loreline.Internal.Lang.Runtime.setField(json, "body", 1092319906, _g)) );
			return json;
		}
		
		
		public override void each(global::Loreline.Internal.Lang.Function handleNode) {
			base.each(handleNode);
			if (( this.body != null )) {
				int _g = 0;
				int _g1 = this.body.length;
				while (( _g < _g1 )) {
					int i = _g++;
					global::Loreline.Runtime.AstNode child = ((global::Loreline.Runtime.AstNode) (this.body[i]) );
					handleNode.__hx_invoke2_o(default(double), child, default(double), this);
					child.each(handleNode);
				}
				
			}
			
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1092319906:
					{
						this.body = ((global::Loreline.Internal.Root.Array<object>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<object>(((global::Loreline.Internal.Root.Array) (@value) ))) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1124892161:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "each", 1124892161)) );
					}
					
					
					case 2082581827:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "toJson", 2082581827)) );
					}
					
					
					case 1092319906:
					{
						return this.body;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("body");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


