// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Runtime {
	public class Script : global::Loreline.Runtime.AstNode {
		
		public Script(global::Loreline.Internal.Lang.EmptyObject empty) : base(global::Loreline.Internal.Lang.EmptyObject.EMPTY) {
		}
		
		
		public Script(long id, global::Loreline.Runtime.Position pos, global::Loreline.Internal.Root.Array body) : base(global::Loreline.Internal.Lang.EmptyObject.EMPTY) {
			global::Loreline.Runtime.Script.__hx_ctor_loreline_Script(this, id, pos, body);
		}
		
		
		protected static void __hx_ctor_loreline_Script(global::Loreline.Runtime.Script __hx_this, long id, global::Loreline.Runtime.Position pos, global::Loreline.Internal.Root.Array body) {
			unchecked {
				__hx_this.indentSize = 2;
				global::Loreline.Runtime.AstNode.__hx_ctor_loreline_AstNode(__hx_this, id, pos, null, null);
				{
					__hx_this.body = body;
				}
				
			}
		}
		
		
		public int indentSize;
		
		public global::Loreline.Internal.Root.Array body;
		
		public override object toJson() {
			object json = base.toJson();
			global::Loreline.Internal.Root.Array _g = new global::Loreline.Internal.Root.Array(new object[]{});
			{
				int _g1 = 0;
				global::Loreline.Internal.Root.Array _g2 = this.body;
				while (( _g1 < _g2.length )) {
					global::Loreline.Runtime.AstNode decl = ((global::Loreline.Runtime.AstNode) (_g2.__get(_g1)) );
					 ++ _g1;
					_g.push(decl.toJson());
				}
				
			}
			
			global::Loreline.Internal.Root.Array __temp_expr1 = ((global::Loreline.Internal.Root.Array) (global::Loreline.Internal.Lang.Runtime.setField(json, "body", 1092319906, _g)) );
			return json;
		}
		
		
		public override string type() {
			return "Script";
		}
		
		
		public virtual void eachExcludingImported(global::Loreline.Internal.Lang.Function handleNode) {
			base.each(handleNode);
			if (( this.body != null )) {
				int _g = 0;
				global::Loreline.Internal.Root.Array _g1 = this.body;
				while (( _g < _g1.length )) {
					global::Loreline.Runtime.AstNode child = ((global::Loreline.Runtime.AstNode) (_g1.__get(_g)) );
					 ++ _g;
					handleNode.__hx_invoke2_o(default(double), child, default(double), this);
					if ( ! (( child is global::Loreline.Runtime.NImportStatement )) ) {
						child.each(handleNode);
					}
					
				}
				
			}
			
		}
		
		
		public override void each(global::Loreline.Internal.Lang.Function handleNode) {
			base.each(handleNode);
			if (( this.body != null )) {
				int _g = 0;
				global::Loreline.Internal.Root.Array _g1 = this.body;
				while (( _g < _g1.length )) {
					global::Loreline.Runtime.AstNode child = ((global::Loreline.Runtime.AstNode) (_g1.__get(_g)) );
					 ++ _g;
					handleNode.__hx_invoke2_o(default(double), child, default(double), this);
					child.each(handleNode);
				}
				
			}
			
		}
		
		
		public virtual global::Loreline.Runtime._Script.ScriptBodyIterator iterator() {
			return new global::Loreline.Runtime._Script.ScriptBodyIterator(((global::Loreline.Internal.Root.Array) (this.body) ));
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1054637901:
					{
						this.indentSize = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1092319906:
					{
						this.body = ((global::Loreline.Internal.Root.Array) (@value) );
						return @value;
					}
					
					
					case 1054637901:
					{
						this.indentSize = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 328878574:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "iterator", 328878574)) );
					}
					
					
					case 1124892161:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "each", 1124892161)) );
					}
					
					
					case 627641210:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "eachExcludingImported", 627641210)) );
					}
					
					
					case 1292432058:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "type", 1292432058)) );
					}
					
					
					case 2082581827:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "toJson", 2082581827)) );
					}
					
					
					case 1092319906:
					{
						return this.body;
					}
					
					
					case 1054637901:
					{
						return this.indentSize;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1054637901:
					{
						return ((double) (this.indentSize) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 2082581827:
					case 1292432058:
					case 1124892161:
					{
						return global::Loreline.Internal.Lang.Runtime.slowCallField(this, field, dynargs);
					}
					
					
					case 328878574:
					{
						return this.iterator();
					}
					
					
					case 627641210:
					{
						this.eachExcludingImported(((global::Loreline.Internal.Lang.Function) (((object) (dynargs[0]) )) ));
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array baseArr) {
			baseArr.push("body");
			baseArr.push("indentSize");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Runtime._Script {
	public class ScriptBodyIterator : global::Loreline.Internal.Lang.HxObject {
		
		public ScriptBodyIterator(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public ScriptBodyIterator(global::Loreline.Internal.Root.Array body) {
			global::Loreline.Runtime._Script.ScriptBodyIterator.__hx_ctor_loreline__Script_ScriptBodyIterator(this, body);
		}
		
		
		protected static void __hx_ctor_loreline__Script_ScriptBodyIterator(global::Loreline.Runtime._Script.ScriptBodyIterator __hx_this, global::Loreline.Internal.Root.Array body) {
			__hx_this.body = body;
			__hx_this.index = 0;
			__hx_this.flatBody = new global::Loreline.Internal.Root.Array(new object[]{});
			__hx_this.fillBody(body);
		}
		
		
		public global::Loreline.Internal.Root.Array body;
		
		public int index;
		
		public global::Loreline.Internal.Root.Array flatBody;
		
		public virtual void fillBody(global::Loreline.Internal.Root.Array body) {
			int _g = 0;
			int _g1 = body.length;
			while (( _g < _g1 )) {
				int i = _g++;
				global::Loreline.Runtime.AstNode node = ((global::Loreline.Runtime.AstNode) (body.__get(i)) );
				if (( node is global::Loreline.Runtime.NImportStatement )) {
					global::Loreline.Runtime.NImportStatement importNode = ((global::Loreline.Runtime.NImportStatement) (node) );
					if (( importNode.script != null )) {
						this.fillBody(importNode.script.body);
					}
					
				}
				
				this.flatBody.push(((global::Loreline.Runtime.AstNode) (body.__get(i)) ));
			}
			
		}
		
		
		public virtual bool hasNext() {
			return ( this.index < this.flatBody.length );
		}
		
		
		public virtual global::Loreline.Runtime.AstNode next() {
			global::Loreline.Runtime.AstNode v = ((global::Loreline.Runtime.AstNode) (this.flatBody.__get(this.index)) );
			this.index++;
			return v;
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1041537810:
					{
						this.index = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 339051259:
					{
						this.flatBody = ((global::Loreline.Internal.Root.Array) (@value) );
						return @value;
					}
					
					
					case 1041537810:
					{
						this.index = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 1092319906:
					{
						this.body = ((global::Loreline.Internal.Root.Array) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1224901875:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "next", 1224901875)) );
					}
					
					
					case 407283053:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "hasNext", 407283053)) );
					}
					
					
					case 1647145669:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "fillBody", 1647145669)) );
					}
					
					
					case 339051259:
					{
						return this.flatBody;
					}
					
					
					case 1041537810:
					{
						return this.index;
					}
					
					
					case 1092319906:
					{
						return this.body;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1041537810:
					{
						return ((double) (this.index) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 1224901875:
					{
						return this.next();
					}
					
					
					case 407283053:
					{
						return this.hasNext();
					}
					
					
					case 1647145669:
					{
						this.fillBody(((global::Loreline.Internal.Root.Array) (((object) (dynargs[0]) )) ));
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array baseArr) {
			baseArr.push("flatBody");
			baseArr.push("index");
			baseArr.push("body");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


