// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public class Const : global::Loreline.Internal.Lang.Enum {
		
		protected Const(int index) : base(index) {
		}
		
		
		public static global::Loreline.Internal.Hscript.Const CInt(int v) {
			return new global::Loreline.Internal.Hscript.Const_CInt(v);
		}
		
		
		public static global::Loreline.Internal.Hscript.Const CFloat(double f) {
			return new global::Loreline.Internal.Hscript.Const_CFloat(f);
		}
		
		
		public static global::Loreline.Internal.Hscript.Const CString(string s) {
			return new global::Loreline.Internal.Hscript.Const_CString(s);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class Const_CInt : global::Loreline.Internal.Hscript.Const {
		
		public Const_CInt(int v) : base(0) {
			this.v = v;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "CInt";
		}
		
		
		public override int GetHashCode() {
			return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(0, new object[]{this.v});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.Const_CInt en = ( other as global::Loreline.Internal.Hscript.Const_CInt );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("CInt", new object[]{this.v});
		}
		
		
		public readonly int v;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class Const_CFloat : global::Loreline.Internal.Hscript.Const {
		
		public Const_CFloat(double f) : base(1) {
			this.f = f;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.f});
		}
		
		
		public override string getTag() {
			return "CFloat";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(1, new object[]{this.f});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.Const_CFloat en = ( other as global::Loreline.Internal.Hscript.Const_CFloat );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.f) ), ((object) (en.f) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("CFloat", new object[]{this.f});
		}
		
		
		public readonly double f;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class Const_CString : global::Loreline.Internal.Hscript.Const {
		
		public Const_CString(string s) : base(2) {
			this.s = s;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.s});
		}
		
		
		public override string getTag() {
			return "CString";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(2, new object[]{this.s});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.Const_CString en = ( other as global::Loreline.Internal.Hscript.Const_CString );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.s) ), ((object) (en.s) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("CString", new object[]{this.s});
		}
		
		
		public readonly string s;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public class ExprDef : global::Loreline.Internal.Lang.Enum {
		
		protected ExprDef(int index) : base(index) {
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EConst(global::Loreline.Internal.Hscript.Const c) {
			return new global::Loreline.Internal.Hscript.ExprDef_EConst(c);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EIdent(string v) {
			return new global::Loreline.Internal.Hscript.ExprDef_EIdent(v);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EVar(string n, global::Loreline.Internal.Hscript.CType t, object e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EVar(n, t, e);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EParent(object e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EParent(e);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EBlock(global::Loreline.Internal.Root.Array e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EBlock(e);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EField(object e, string f) {
			return new global::Loreline.Internal.Hscript.ExprDef_EField(e, f);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EBinop(string op, object e1, object e2) {
			return new global::Loreline.Internal.Hscript.ExprDef_EBinop(op, e1, e2);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EUnop(string op, bool prefix, object e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EUnop(op, prefix, e);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef ECall(object e, global::Loreline.Internal.Root.Array @params) {
			return new global::Loreline.Internal.Hscript.ExprDef_ECall(e, @params);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EIf(object cond, object e1, object e2) {
			return new global::Loreline.Internal.Hscript.ExprDef_EIf(cond, e1, e2);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EWhile(object cond, object e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EWhile(cond, e);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EFor(string v, object it, object e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EFor(v, it, e);
		}
		
		
		public static readonly global::Loreline.Internal.Hscript.ExprDef EBreak = new global::Loreline.Internal.Hscript.ExprDef_EBreak();
		
		public static readonly global::Loreline.Internal.Hscript.ExprDef EContinue = new global::Loreline.Internal.Hscript.ExprDef_EContinue();
		
		public static global::Loreline.Internal.Hscript.ExprDef EFunction(global::Loreline.Internal.Root.Array args, object e, string name, global::Loreline.Internal.Hscript.CType ret) {
			return new global::Loreline.Internal.Hscript.ExprDef_EFunction(args, e, name, ret);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EReturn(object e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EReturn(e);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EArray(object e, object index) {
			return new global::Loreline.Internal.Hscript.ExprDef_EArray(e, index);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EArrayDecl(global::Loreline.Internal.Root.Array e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EArrayDecl(e);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef ENew(string cl, global::Loreline.Internal.Root.Array @params) {
			return new global::Loreline.Internal.Hscript.ExprDef_ENew(cl, @params);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EThrow(object e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EThrow(e);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef ETry(object e, string v, global::Loreline.Internal.Hscript.CType t, object ecatch) {
			return new global::Loreline.Internal.Hscript.ExprDef_ETry(e, v, t, ecatch);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EObject(global::Loreline.Internal.Root.Array fl) {
			return new global::Loreline.Internal.Hscript.ExprDef_EObject(fl);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef ETernary(object cond, object e1, object e2) {
			return new global::Loreline.Internal.Hscript.ExprDef_ETernary(cond, e1, e2);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef ESwitch(object e, global::Loreline.Internal.Root.Array cases, object defaultExpr) {
			return new global::Loreline.Internal.Hscript.ExprDef_ESwitch(e, cases, defaultExpr);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EDoWhile(object cond, object e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EDoWhile(cond, e);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef EMeta(string name, global::Loreline.Internal.Root.Array args, object e) {
			return new global::Loreline.Internal.Hscript.ExprDef_EMeta(name, args, e);
		}
		
		
		public static global::Loreline.Internal.Hscript.ExprDef ECheckType(object e, global::Loreline.Internal.Hscript.CType t) {
			return new global::Loreline.Internal.Hscript.ExprDef_ECheckType(e, t);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EConst : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EConst(global::Loreline.Internal.Hscript.Const c) : base(0) {
			this.c = c;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.c});
		}
		
		
		public override string getTag() {
			return "EConst";
		}
		
		
		public override int GetHashCode() {
			return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(0, new object[]{this.c});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EConst en = ( other as global::Loreline.Internal.Hscript.ExprDef_EConst );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.c) ), ((object) (en.c) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EConst", new object[]{this.c});
		}
		
		
		public readonly global::Loreline.Internal.Hscript.Const c;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EIdent : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EIdent(string v) : base(1) {
			this.v = v;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "EIdent";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(1, new object[]{this.v});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EIdent en = ( other as global::Loreline.Internal.Hscript.ExprDef_EIdent );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EIdent", new object[]{this.v});
		}
		
		
		public readonly string v;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EVar : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EVar(string n, global::Loreline.Internal.Hscript.CType t, object e) : base(2) {
			this.n = n;
			this.t = t;
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.n, this.t, this.e});
		}
		
		
		public override string getTag() {
			return "EVar";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(2, new object[]{this.n, this.t, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EVar en = ( other as global::Loreline.Internal.Hscript.ExprDef_EVar );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.n) ), ((object) (en.n) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EVar", new object[]{this.n, this.t, this.e});
		}
		
		
		public readonly string n;
		
		public readonly global::Loreline.Internal.Hscript.CType t;
		
		public readonly object e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EParent : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EParent(object e) : base(3) {
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e});
		}
		
		
		public override string getTag() {
			return "EParent";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(3, new object[]{this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EParent en = ( other as global::Loreline.Internal.Hscript.ExprDef_EParent );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EParent", new object[]{this.e});
		}
		
		
		public readonly object e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EBlock : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EBlock(global::Loreline.Internal.Root.Array e) : base(4) {
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e});
		}
		
		
		public override string getTag() {
			return "EBlock";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(4, new object[]{this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EBlock en = ( other as global::Loreline.Internal.Hscript.ExprDef_EBlock );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EBlock", new object[]{this.e});
		}
		
		
		public readonly global::Loreline.Internal.Root.Array e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EField : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EField(object e, string f) : base(5) {
			this.e = e;
			this.f = f;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e, this.f});
		}
		
		
		public override string getTag() {
			return "EField";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(5, new object[]{this.e, this.f});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EField en = ( other as global::Loreline.Internal.Hscript.ExprDef_EField );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.f) ), ((object) (en.f) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EField", new object[]{this.e, this.f});
		}
		
		
		public readonly object e;
		
		public readonly string f;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EBinop : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EBinop(string op, object e1, object e2) : base(6) {
			this.op = op;
			this.e1 = e1;
			this.e2 = e2;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.op, this.e1, this.e2});
		}
		
		
		public override string getTag() {
			return "EBinop";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(6, new object[]{this.op, this.e1, this.e2});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EBinop en = ( other as global::Loreline.Internal.Hscript.ExprDef_EBinop );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.op) ), ((object) (en.op) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e1) ), ((object) (en.e1) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e2) ), ((object) (en.e2) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EBinop", new object[]{this.op, this.e1, this.e2});
		}
		
		
		public readonly string op;
		
		public readonly object e1;
		
		public readonly object e2;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EUnop : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EUnop(string op, bool prefix, object e) : base(7) {
			this.op = op;
			this.prefix = prefix;
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.op, this.prefix, this.e});
		}
		
		
		public override string getTag() {
			return "EUnop";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(7, new object[]{this.op, this.prefix, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EUnop en = ( other as global::Loreline.Internal.Hscript.ExprDef_EUnop );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.op) ), ((object) (en.op) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.prefix) ), ((object) (en.prefix) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EUnop", new object[]{this.op, this.prefix, this.e});
		}
		
		
		public readonly string op;
		
		public readonly bool prefix;
		
		public readonly object e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_ECall : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_ECall(object e, global::Loreline.Internal.Root.Array @params) : base(8) {
			this.e = e;
			this.@params = @params;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e, this.@params});
		}
		
		
		public override string getTag() {
			return "ECall";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(8, new object[]{this.e, this.@params});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_ECall en = ( other as global::Loreline.Internal.Hscript.ExprDef_ECall );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.@params) ), ((object) (en.@params) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("ECall", new object[]{this.e, this.@params});
		}
		
		
		public readonly object e;
		
		public readonly global::Loreline.Internal.Root.Array @params;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EIf : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EIf(object cond, object e1, object e2) : base(9) {
			this.cond = cond;
			this.e1 = e1;
			this.e2 = e2;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.cond, this.e1, this.e2});
		}
		
		
		public override string getTag() {
			return "EIf";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(9, new object[]{this.cond, this.e1, this.e2});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EIf en = ( other as global::Loreline.Internal.Hscript.ExprDef_EIf );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.cond) ), ((object) (en.cond) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e1) ), ((object) (en.e1) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e2) ), ((object) (en.e2) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EIf", new object[]{this.cond, this.e1, this.e2});
		}
		
		
		public readonly object cond;
		
		public readonly object e1;
		
		public readonly object e2;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EWhile : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EWhile(object cond, object e) : base(10) {
			this.cond = cond;
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.cond, this.e});
		}
		
		
		public override string getTag() {
			return "EWhile";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(10, new object[]{this.cond, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EWhile en = ( other as global::Loreline.Internal.Hscript.ExprDef_EWhile );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.cond) ), ((object) (en.cond) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EWhile", new object[]{this.cond, this.e});
		}
		
		
		public readonly object cond;
		
		public readonly object e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EFor : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EFor(string v, object it, object e) : base(11) {
			this.v = v;
			this.it = it;
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.v, this.it, this.e});
		}
		
		
		public override string getTag() {
			return "EFor";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(11, new object[]{this.v, this.it, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EFor en = ( other as global::Loreline.Internal.Hscript.ExprDef_EFor );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.it) ), ((object) (en.it) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EFor", new object[]{this.v, this.it, this.e});
		}
		
		
		public readonly string v;
		
		public readonly object it;
		
		public readonly object e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EBreak : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EBreak() : base(12) {
		}
		
		
		public override string getTag() {
			return "EBreak";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EContinue : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EContinue() : base(13) {
		}
		
		
		public override string getTag() {
			return "EContinue";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EFunction : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EFunction(global::Loreline.Internal.Root.Array args, object e, string name, global::Loreline.Internal.Hscript.CType ret) : base(14) {
			this.args = args;
			this.e = e;
			this.name = name;
			this.ret = ret;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.args, this.e, this.name, this.ret});
		}
		
		
		public override string getTag() {
			return "EFunction";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(14, new object[]{this.args, this.e, this.name, this.ret});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EFunction en = ( other as global::Loreline.Internal.Hscript.ExprDef_EFunction );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.args) ), ((object) (en.args) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.name) ), ((object) (en.name) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.ret) ), ((object) (en.ret) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EFunction", new object[]{this.args, this.e, this.name, this.ret});
		}
		
		
		public readonly global::Loreline.Internal.Root.Array args;
		
		public readonly object e;
		
		public readonly string name;
		
		public readonly global::Loreline.Internal.Hscript.CType ret;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EReturn : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EReturn(object e) : base(15) {
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e});
		}
		
		
		public override string getTag() {
			return "EReturn";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(15, new object[]{this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EReturn en = ( other as global::Loreline.Internal.Hscript.ExprDef_EReturn );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EReturn", new object[]{this.e});
		}
		
		
		public readonly object e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EArray : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EArray(object e, object index) : base(16) {
			this.e = e;
			this.index = index;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e, this.index});
		}
		
		
		public override string getTag() {
			return "EArray";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(16, new object[]{this.e, this.index});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EArray en = ( other as global::Loreline.Internal.Hscript.ExprDef_EArray );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.index) ), ((object) (en.index) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EArray", new object[]{this.e, this.index});
		}
		
		
		public readonly object e;
		
		public readonly object index;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EArrayDecl : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EArrayDecl(global::Loreline.Internal.Root.Array e) : base(17) {
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e});
		}
		
		
		public override string getTag() {
			return "EArrayDecl";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(17, new object[]{this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EArrayDecl en = ( other as global::Loreline.Internal.Hscript.ExprDef_EArrayDecl );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EArrayDecl", new object[]{this.e});
		}
		
		
		public readonly global::Loreline.Internal.Root.Array e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_ENew : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_ENew(string cl, global::Loreline.Internal.Root.Array @params) : base(18) {
			this.cl = cl;
			this.@params = @params;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.cl, this.@params});
		}
		
		
		public override string getTag() {
			return "ENew";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(18, new object[]{this.cl, this.@params});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_ENew en = ( other as global::Loreline.Internal.Hscript.ExprDef_ENew );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.cl) ), ((object) (en.cl) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.@params) ), ((object) (en.@params) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("ENew", new object[]{this.cl, this.@params});
		}
		
		
		public readonly string cl;
		
		public readonly global::Loreline.Internal.Root.Array @params;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EThrow : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EThrow(object e) : base(19) {
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e});
		}
		
		
		public override string getTag() {
			return "EThrow";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(19, new object[]{this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EThrow en = ( other as global::Loreline.Internal.Hscript.ExprDef_EThrow );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EThrow", new object[]{this.e});
		}
		
		
		public readonly object e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_ETry : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_ETry(object e, string v, global::Loreline.Internal.Hscript.CType t, object ecatch) : base(20) {
			this.e = e;
			this.v = v;
			this.t = t;
			this.ecatch = ecatch;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e, this.v, this.t, this.ecatch});
		}
		
		
		public override string getTag() {
			return "ETry";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(20, new object[]{this.e, this.v, this.t, this.ecatch});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_ETry en = ( other as global::Loreline.Internal.Hscript.ExprDef_ETry );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.ecatch) ), ((object) (en.ecatch) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("ETry", new object[]{this.e, this.v, this.t, this.ecatch});
		}
		
		
		public readonly object e;
		
		public readonly string v;
		
		public readonly global::Loreline.Internal.Hscript.CType t;
		
		public readonly object ecatch;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EObject : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EObject(global::Loreline.Internal.Root.Array fl) : base(21) {
			this.fl = fl;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.fl});
		}
		
		
		public override string getTag() {
			return "EObject";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(21, new object[]{this.fl});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EObject en = ( other as global::Loreline.Internal.Hscript.ExprDef_EObject );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.fl) ), ((object) (en.fl) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EObject", new object[]{this.fl});
		}
		
		
		public readonly global::Loreline.Internal.Root.Array fl;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_ETernary : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_ETernary(object cond, object e1, object e2) : base(22) {
			this.cond = cond;
			this.e1 = e1;
			this.e2 = e2;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.cond, this.e1, this.e2});
		}
		
		
		public override string getTag() {
			return "ETernary";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(22, new object[]{this.cond, this.e1, this.e2});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_ETernary en = ( other as global::Loreline.Internal.Hscript.ExprDef_ETernary );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.cond) ), ((object) (en.cond) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e1) ), ((object) (en.e1) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e2) ), ((object) (en.e2) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("ETernary", new object[]{this.cond, this.e1, this.e2});
		}
		
		
		public readonly object cond;
		
		public readonly object e1;
		
		public readonly object e2;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_ESwitch : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_ESwitch(object e, global::Loreline.Internal.Root.Array cases, object defaultExpr) : base(23) {
			this.e = e;
			this.cases = cases;
			this.defaultExpr = defaultExpr;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e, this.cases, this.defaultExpr});
		}
		
		
		public override string getTag() {
			return "ESwitch";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(23, new object[]{this.e, this.cases, this.defaultExpr});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_ESwitch en = ( other as global::Loreline.Internal.Hscript.ExprDef_ESwitch );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.cases) ), ((object) (en.cases) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.defaultExpr) ), ((object) (en.defaultExpr) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("ESwitch", new object[]{this.e, this.cases, this.defaultExpr});
		}
		
		
		public readonly object e;
		
		public readonly global::Loreline.Internal.Root.Array cases;
		
		public readonly object defaultExpr;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EDoWhile : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EDoWhile(object cond, object e) : base(24) {
			this.cond = cond;
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.cond, this.e});
		}
		
		
		public override string getTag() {
			return "EDoWhile";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(24, new object[]{this.cond, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EDoWhile en = ( other as global::Loreline.Internal.Hscript.ExprDef_EDoWhile );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.cond) ), ((object) (en.cond) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EDoWhile", new object[]{this.cond, this.e});
		}
		
		
		public readonly object cond;
		
		public readonly object e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_EMeta : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_EMeta(string name, global::Loreline.Internal.Root.Array args, object e) : base(25) {
			this.name = name;
			this.args = args;
			this.e = e;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.name, this.args, this.e});
		}
		
		
		public override string getTag() {
			return "EMeta";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(25, new object[]{this.name, this.args, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_EMeta en = ( other as global::Loreline.Internal.Hscript.ExprDef_EMeta );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.name) ), ((object) (en.name) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.args) ), ((object) (en.args) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EMeta", new object[]{this.name, this.args, this.e});
		}
		
		
		public readonly string name;
		
		public readonly global::Loreline.Internal.Root.Array args;
		
		public readonly object e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ExprDef_ECheckType : global::Loreline.Internal.Hscript.ExprDef {
		
		public ExprDef_ECheckType(object e, global::Loreline.Internal.Hscript.CType t) : base(26) {
			this.e = e;
			this.t = t;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.e, this.t});
		}
		
		
		public override string getTag() {
			return "ECheckType";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(26, new object[]{this.e, this.t});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ExprDef_ECheckType en = ( other as global::Loreline.Internal.Hscript.ExprDef_ECheckType );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("ECheckType", new object[]{this.e, this.t});
		}
		
		
		public readonly object e;
		
		public readonly global::Loreline.Internal.Hscript.CType t;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public class CType : global::Loreline.Internal.Lang.Enum {
		
		protected CType(int index) : base(index) {
		}
		
		
		public static global::Loreline.Internal.Hscript.CType CTPath(global::Loreline.Internal.Root.Array path, global::Loreline.Internal.Root.Array @params) {
			return new global::Loreline.Internal.Hscript.CType_CTPath(path, @params);
		}
		
		
		public static global::Loreline.Internal.Hscript.CType CTFun(global::Loreline.Internal.Root.Array args, global::Loreline.Internal.Hscript.CType ret) {
			return new global::Loreline.Internal.Hscript.CType_CTFun(args, ret);
		}
		
		
		public static global::Loreline.Internal.Hscript.CType CTAnon(global::Loreline.Internal.Root.Array fields) {
			return new global::Loreline.Internal.Hscript.CType_CTAnon(fields);
		}
		
		
		public static global::Loreline.Internal.Hscript.CType CTParent(global::Loreline.Internal.Hscript.CType t) {
			return new global::Loreline.Internal.Hscript.CType_CTParent(t);
		}
		
		
		public static global::Loreline.Internal.Hscript.CType CTOpt(global::Loreline.Internal.Hscript.CType t) {
			return new global::Loreline.Internal.Hscript.CType_CTOpt(t);
		}
		
		
		public static global::Loreline.Internal.Hscript.CType CTNamed(string n, global::Loreline.Internal.Hscript.CType t) {
			return new global::Loreline.Internal.Hscript.CType_CTNamed(n, t);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class CType_CTPath : global::Loreline.Internal.Hscript.CType {
		
		public CType_CTPath(global::Loreline.Internal.Root.Array path, global::Loreline.Internal.Root.Array @params) : base(0) {
			this.path = path;
			this.@params = @params;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.path, this.@params});
		}
		
		
		public override string getTag() {
			return "CTPath";
		}
		
		
		public override int GetHashCode() {
			return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(0, new object[]{this.path, this.@params});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.CType_CTPath en = ( other as global::Loreline.Internal.Hscript.CType_CTPath );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.path) ), ((object) (en.path) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.@params) ), ((object) (en.@params) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("CTPath", new object[]{this.path, this.@params});
		}
		
		
		public readonly global::Loreline.Internal.Root.Array path;
		
		public readonly global::Loreline.Internal.Root.Array @params;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class CType_CTFun : global::Loreline.Internal.Hscript.CType {
		
		public CType_CTFun(global::Loreline.Internal.Root.Array args, global::Loreline.Internal.Hscript.CType ret) : base(1) {
			this.args = args;
			this.ret = ret;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.args, this.ret});
		}
		
		
		public override string getTag() {
			return "CTFun";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(1, new object[]{this.args, this.ret});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.CType_CTFun en = ( other as global::Loreline.Internal.Hscript.CType_CTFun );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.args) ), ((object) (en.args) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.ret) ), ((object) (en.ret) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("CTFun", new object[]{this.args, this.ret});
		}
		
		
		public readonly global::Loreline.Internal.Root.Array args;
		
		public readonly global::Loreline.Internal.Hscript.CType ret;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class CType_CTAnon : global::Loreline.Internal.Hscript.CType {
		
		public CType_CTAnon(global::Loreline.Internal.Root.Array fields) : base(2) {
			this.fields = fields;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.fields});
		}
		
		
		public override string getTag() {
			return "CTAnon";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(2, new object[]{this.fields});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.CType_CTAnon en = ( other as global::Loreline.Internal.Hscript.CType_CTAnon );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.fields) ), ((object) (en.fields) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("CTAnon", new object[]{this.fields});
		}
		
		
		public readonly global::Loreline.Internal.Root.Array fields;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class CType_CTParent : global::Loreline.Internal.Hscript.CType {
		
		public CType_CTParent(global::Loreline.Internal.Hscript.CType t) : base(3) {
			this.t = t;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.t});
		}
		
		
		public override string getTag() {
			return "CTParent";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(3, new object[]{this.t});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.CType_CTParent en = ( other as global::Loreline.Internal.Hscript.CType_CTParent );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("CTParent", new object[]{this.t});
		}
		
		
		public readonly global::Loreline.Internal.Hscript.CType t;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class CType_CTOpt : global::Loreline.Internal.Hscript.CType {
		
		public CType_CTOpt(global::Loreline.Internal.Hscript.CType t) : base(4) {
			this.t = t;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.t});
		}
		
		
		public override string getTag() {
			return "CTOpt";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(4, new object[]{this.t});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.CType_CTOpt en = ( other as global::Loreline.Internal.Hscript.CType_CTOpt );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("CTOpt", new object[]{this.t});
		}
		
		
		public readonly global::Loreline.Internal.Hscript.CType t;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class CType_CTNamed : global::Loreline.Internal.Hscript.CType {
		
		public CType_CTNamed(string n, global::Loreline.Internal.Hscript.CType t) : base(5) {
			this.n = n;
			this.t = t;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.n, this.t});
		}
		
		
		public override string getTag() {
			return "CTNamed";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(5, new object[]{this.n, this.t});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.CType_CTNamed en = ( other as global::Loreline.Internal.Hscript.CType_CTNamed );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.n) ), ((object) (en.n) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("CTNamed", new object[]{this.n, this.t});
		}
		
		
		public readonly string n;
		
		public readonly global::Loreline.Internal.Hscript.CType t;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public class Error : global::Loreline.Internal.Lang.HxObject {
		
		public Error(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public Error(global::Loreline.Internal.Hscript.ErrorDef e, int pmin, int pmax, string origin, int line) {
			global::Loreline.Internal.Hscript.Error.__hx_ctor_hscript_Error(this, e, pmin, pmax, origin, line);
		}
		
		
		protected static void __hx_ctor_hscript_Error(global::Loreline.Internal.Hscript.Error __hx_this, global::Loreline.Internal.Hscript.ErrorDef e, int pmin, int pmax, string origin, int line) {
			__hx_this.e = e;
			__hx_this.pmin = pmin;
			__hx_this.pmax = pmax;
			__hx_this.origin = origin;
			__hx_this.line = line;
		}
		
		
		public global::Loreline.Internal.Hscript.ErrorDef e;
		
		public int pmin;
		
		public int pmax;
		
		public string origin;
		
		public int line;
		
		public virtual string toString() {
			return global::Loreline.Internal.Hscript.Printer.errorToString(this);
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1202919412:
					{
						this.line = ((int) (@value) );
						return @value;
					}
					
					
					case 1247473716:
					{
						this.pmax = ((int) (@value) );
						return @value;
					}
					
					
					case 1247475490:
					{
						this.pmin = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1202919412:
					{
						this.line = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 1258363366:
					{
						this.origin = global::Loreline.Internal.Lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 1247473716:
					{
						this.pmax = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 1247475490:
					{
						this.pmin = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 101:
					{
						this.e = ((global::Loreline.Internal.Hscript.ErrorDef) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 946786476:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 1202919412:
					{
						return this.line;
					}
					
					
					case 1258363366:
					{
						return this.origin;
					}
					
					
					case 1247473716:
					{
						return this.pmax;
					}
					
					
					case 1247475490:
					{
						return this.pmin;
					}
					
					
					case 101:
					{
						return this.e;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1202919412:
					{
						return ((double) (this.line) );
					}
					
					
					case 1247473716:
					{
						return ((double) (this.pmax) );
					}
					
					
					case 1247475490:
					{
						return ((double) (this.pmin) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 946786476:
					{
						return this.toString();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array baseArr) {
			baseArr.push("line");
			baseArr.push("origin");
			baseArr.push("pmax");
			baseArr.push("pmin");
			baseArr.push("e");
			base.__hx_getFields(baseArr);
		}
		
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public class ErrorDef : global::Loreline.Internal.Lang.Enum {
		
		protected ErrorDef(int index) : base(index) {
		}
		
		
		public static global::Loreline.Internal.Hscript.ErrorDef EInvalidChar(int c) {
			return new global::Loreline.Internal.Hscript.ErrorDef_EInvalidChar(c);
		}
		
		
		public static global::Loreline.Internal.Hscript.ErrorDef EUnexpected(string s) {
			return new global::Loreline.Internal.Hscript.ErrorDef_EUnexpected(s);
		}
		
		
		public static readonly global::Loreline.Internal.Hscript.ErrorDef EUnterminatedString = new global::Loreline.Internal.Hscript.ErrorDef_EUnterminatedString();
		
		public static readonly global::Loreline.Internal.Hscript.ErrorDef EUnterminatedComment = new global::Loreline.Internal.Hscript.ErrorDef_EUnterminatedComment();
		
		public static global::Loreline.Internal.Hscript.ErrorDef EInvalidPreprocessor(string msg) {
			return new global::Loreline.Internal.Hscript.ErrorDef_EInvalidPreprocessor(msg);
		}
		
		
		public static global::Loreline.Internal.Hscript.ErrorDef EUnknownVariable(string v) {
			return new global::Loreline.Internal.Hscript.ErrorDef_EUnknownVariable(v);
		}
		
		
		public static global::Loreline.Internal.Hscript.ErrorDef EInvalidIterator(string v) {
			return new global::Loreline.Internal.Hscript.ErrorDef_EInvalidIterator(v);
		}
		
		
		public static global::Loreline.Internal.Hscript.ErrorDef EInvalidOp(string op) {
			return new global::Loreline.Internal.Hscript.ErrorDef_EInvalidOp(op);
		}
		
		
		public static global::Loreline.Internal.Hscript.ErrorDef EInvalidAccess(string f) {
			return new global::Loreline.Internal.Hscript.ErrorDef_EInvalidAccess(f);
		}
		
		
		public static global::Loreline.Internal.Hscript.ErrorDef ECustom(string msg) {
			return new global::Loreline.Internal.Hscript.ErrorDef_ECustom(msg);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ErrorDef_EInvalidChar : global::Loreline.Internal.Hscript.ErrorDef {
		
		public ErrorDef_EInvalidChar(int c) : base(0) {
			this.c = c;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.c});
		}
		
		
		public override string getTag() {
			return "EInvalidChar";
		}
		
		
		public override int GetHashCode() {
			return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(0, new object[]{this.c});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ErrorDef_EInvalidChar en = ( other as global::Loreline.Internal.Hscript.ErrorDef_EInvalidChar );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.c) ), ((object) (en.c) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EInvalidChar", new object[]{this.c});
		}
		
		
		public readonly int c;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ErrorDef_EUnexpected : global::Loreline.Internal.Hscript.ErrorDef {
		
		public ErrorDef_EUnexpected(string s) : base(1) {
			this.s = s;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.s});
		}
		
		
		public override string getTag() {
			return "EUnexpected";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(1, new object[]{this.s});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ErrorDef_EUnexpected en = ( other as global::Loreline.Internal.Hscript.ErrorDef_EUnexpected );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.s) ), ((object) (en.s) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EUnexpected", new object[]{this.s});
		}
		
		
		public readonly string s;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ErrorDef_EUnterminatedString : global::Loreline.Internal.Hscript.ErrorDef {
		
		public ErrorDef_EUnterminatedString() : base(2) {
		}
		
		
		public override string getTag() {
			return "EUnterminatedString";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ErrorDef_EUnterminatedComment : global::Loreline.Internal.Hscript.ErrorDef {
		
		public ErrorDef_EUnterminatedComment() : base(3) {
		}
		
		
		public override string getTag() {
			return "EUnterminatedComment";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ErrorDef_EInvalidPreprocessor : global::Loreline.Internal.Hscript.ErrorDef {
		
		public ErrorDef_EInvalidPreprocessor(string msg) : base(4) {
			this.msg = msg;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.msg});
		}
		
		
		public override string getTag() {
			return "EInvalidPreprocessor";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(4, new object[]{this.msg});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ErrorDef_EInvalidPreprocessor en = ( other as global::Loreline.Internal.Hscript.ErrorDef_EInvalidPreprocessor );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.msg) ), ((object) (en.msg) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EInvalidPreprocessor", new object[]{this.msg});
		}
		
		
		public readonly string msg;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ErrorDef_EUnknownVariable : global::Loreline.Internal.Hscript.ErrorDef {
		
		public ErrorDef_EUnknownVariable(string v) : base(5) {
			this.v = v;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "EUnknownVariable";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(5, new object[]{this.v});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ErrorDef_EUnknownVariable en = ( other as global::Loreline.Internal.Hscript.ErrorDef_EUnknownVariable );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EUnknownVariable", new object[]{this.v});
		}
		
		
		public readonly string v;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ErrorDef_EInvalidIterator : global::Loreline.Internal.Hscript.ErrorDef {
		
		public ErrorDef_EInvalidIterator(string v) : base(6) {
			this.v = v;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "EInvalidIterator";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(6, new object[]{this.v});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ErrorDef_EInvalidIterator en = ( other as global::Loreline.Internal.Hscript.ErrorDef_EInvalidIterator );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EInvalidIterator", new object[]{this.v});
		}
		
		
		public readonly string v;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ErrorDef_EInvalidOp : global::Loreline.Internal.Hscript.ErrorDef {
		
		public ErrorDef_EInvalidOp(string op) : base(7) {
			this.op = op;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.op});
		}
		
		
		public override string getTag() {
			return "EInvalidOp";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(7, new object[]{this.op});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ErrorDef_EInvalidOp en = ( other as global::Loreline.Internal.Hscript.ErrorDef_EInvalidOp );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.op) ), ((object) (en.op) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EInvalidOp", new object[]{this.op});
		}
		
		
		public readonly string op;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ErrorDef_EInvalidAccess : global::Loreline.Internal.Hscript.ErrorDef {
		
		public ErrorDef_EInvalidAccess(string f) : base(8) {
			this.f = f;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.f});
		}
		
		
		public override string getTag() {
			return "EInvalidAccess";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(8, new object[]{this.f});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ErrorDef_EInvalidAccess en = ( other as global::Loreline.Internal.Hscript.ErrorDef_EInvalidAccess );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.f) ), ((object) (en.f) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("EInvalidAccess", new object[]{this.f});
		}
		
		
		public readonly string f;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ErrorDef_ECustom : global::Loreline.Internal.Hscript.ErrorDef {
		
		public ErrorDef_ECustom(string msg) : base(9) {
			this.msg = msg;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.msg});
		}
		
		
		public override string getTag() {
			return "ECustom";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(9, new object[]{this.msg});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ErrorDef_ECustom en = ( other as global::Loreline.Internal.Hscript.ErrorDef_ECustom );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.msg) ), ((object) (en.msg) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("ECustom", new object[]{this.msg});
		}
		
		
		public readonly string msg;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public class ModuleDecl : global::Loreline.Internal.Lang.Enum {
		
		protected ModuleDecl(int index) : base(index) {
		}
		
		
		public static global::Loreline.Internal.Hscript.ModuleDecl DPackage(global::Loreline.Internal.Root.Array path) {
			return new global::Loreline.Internal.Hscript.ModuleDecl_DPackage(path);
		}
		
		
		public static global::Loreline.Internal.Hscript.ModuleDecl DImport(global::Loreline.Internal.Root.Array path, object everything) {
			return new global::Loreline.Internal.Hscript.ModuleDecl_DImport(path, everything);
		}
		
		
		public static global::Loreline.Internal.Hscript.ModuleDecl DClass(object c) {
			return new global::Loreline.Internal.Hscript.ModuleDecl_DClass(c);
		}
		
		
		public static global::Loreline.Internal.Hscript.ModuleDecl DTypedef(object c) {
			return new global::Loreline.Internal.Hscript.ModuleDecl_DTypedef(c);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ModuleDecl_DPackage : global::Loreline.Internal.Hscript.ModuleDecl {
		
		public ModuleDecl_DPackage(global::Loreline.Internal.Root.Array path) : base(0) {
			this.path = path;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.path});
		}
		
		
		public override string getTag() {
			return "DPackage";
		}
		
		
		public override int GetHashCode() {
			return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(0, new object[]{this.path});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ModuleDecl_DPackage en = ( other as global::Loreline.Internal.Hscript.ModuleDecl_DPackage );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.path) ), ((object) (en.path) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("DPackage", new object[]{this.path});
		}
		
		
		public readonly global::Loreline.Internal.Root.Array path;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ModuleDecl_DImport : global::Loreline.Internal.Hscript.ModuleDecl {
		
		public ModuleDecl_DImport(global::Loreline.Internal.Root.Array path, object everything) : base(1) {
			this.path = path;
			this.everything = everything;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.path, this.everything});
		}
		
		
		public override string getTag() {
			return "DImport";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(1, new object[]{this.path, this.everything});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ModuleDecl_DImport en = ( other as global::Loreline.Internal.Hscript.ModuleDecl_DImport );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.path) ), ((object) (en.path) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.everything) ), ((object) (en.everything) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("DImport", new object[]{this.path, this.everything});
		}
		
		
		public readonly global::Loreline.Internal.Root.Array path;
		
		public readonly object everything;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ModuleDecl_DClass : global::Loreline.Internal.Hscript.ModuleDecl {
		
		public ModuleDecl_DClass(object c) : base(2) {
			this.c = c;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.c});
		}
		
		
		public override string getTag() {
			return "DClass";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(2, new object[]{this.c});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ModuleDecl_DClass en = ( other as global::Loreline.Internal.Hscript.ModuleDecl_DClass );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.c) ), ((object) (en.c) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("DClass", new object[]{this.c});
		}
		
		
		public readonly object c;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class ModuleDecl_DTypedef : global::Loreline.Internal.Hscript.ModuleDecl {
		
		public ModuleDecl_DTypedef(object c) : base(3) {
			this.c = c;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.c});
		}
		
		
		public override string getTag() {
			return "DTypedef";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(3, new object[]{this.c});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.ModuleDecl_DTypedef en = ( other as global::Loreline.Internal.Hscript.ModuleDecl_DTypedef );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.c) ), ((object) (en.c) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("DTypedef", new object[]{this.c});
		}
		
		
		public readonly object c;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public class FieldAccess : global::Loreline.Internal.Lang.Enum {
		
		protected FieldAccess(int index) : base(index) {
		}
		
		
		public static readonly global::Loreline.Internal.Hscript.FieldAccess APublic = new global::Loreline.Internal.Hscript.FieldAccess_APublic();
		
		public static readonly global::Loreline.Internal.Hscript.FieldAccess APrivate = new global::Loreline.Internal.Hscript.FieldAccess_APrivate();
		
		public static readonly global::Loreline.Internal.Hscript.FieldAccess AInline = new global::Loreline.Internal.Hscript.FieldAccess_AInline();
		
		public static readonly global::Loreline.Internal.Hscript.FieldAccess AOverride = new global::Loreline.Internal.Hscript.FieldAccess_AOverride();
		
		public static readonly global::Loreline.Internal.Hscript.FieldAccess AStatic = new global::Loreline.Internal.Hscript.FieldAccess_AStatic();
		
		public static readonly global::Loreline.Internal.Hscript.FieldAccess AMacro = new global::Loreline.Internal.Hscript.FieldAccess_AMacro();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class FieldAccess_APublic : global::Loreline.Internal.Hscript.FieldAccess {
		
		public FieldAccess_APublic() : base(0) {
		}
		
		
		public override string getTag() {
			return "APublic";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class FieldAccess_APrivate : global::Loreline.Internal.Hscript.FieldAccess {
		
		public FieldAccess_APrivate() : base(1) {
		}
		
		
		public override string getTag() {
			return "APrivate";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class FieldAccess_AInline : global::Loreline.Internal.Hscript.FieldAccess {
		
		public FieldAccess_AInline() : base(2) {
		}
		
		
		public override string getTag() {
			return "AInline";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class FieldAccess_AOverride : global::Loreline.Internal.Hscript.FieldAccess {
		
		public FieldAccess_AOverride() : base(3) {
		}
		
		
		public override string getTag() {
			return "AOverride";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class FieldAccess_AStatic : global::Loreline.Internal.Hscript.FieldAccess {
		
		public FieldAccess_AStatic() : base(4) {
		}
		
		
		public override string getTag() {
			return "AStatic";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class FieldAccess_AMacro : global::Loreline.Internal.Hscript.FieldAccess {
		
		public FieldAccess_AMacro() : base(5) {
		}
		
		
		public override string getTag() {
			return "AMacro";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public class FieldKind : global::Loreline.Internal.Lang.Enum {
		
		protected FieldKind(int index) : base(index) {
		}
		
		
		public static global::Loreline.Internal.Hscript.FieldKind KFunction(object f) {
			return new global::Loreline.Internal.Hscript.FieldKind_KFunction(f);
		}
		
		
		public static global::Loreline.Internal.Hscript.FieldKind KVar(object v) {
			return new global::Loreline.Internal.Hscript.FieldKind_KVar(v);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class FieldKind_KFunction : global::Loreline.Internal.Hscript.FieldKind {
		
		public FieldKind_KFunction(object f) : base(0) {
			this.f = f;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.f});
		}
		
		
		public override string getTag() {
			return "KFunction";
		}
		
		
		public override int GetHashCode() {
			return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(0, new object[]{this.f});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.FieldKind_KFunction en = ( other as global::Loreline.Internal.Hscript.FieldKind_KFunction );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.f) ), ((object) (en.f) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("KFunction", new object[]{this.f});
		}
		
		
		public readonly object f;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public sealed class FieldKind_KVar : global::Loreline.Internal.Hscript.FieldKind {
		
		public FieldKind_KVar(object v) : base(1) {
			this.v = v;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "KVar";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(1, new object[]{this.v});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.Hscript.FieldKind_KVar en = ( other as global::Loreline.Internal.Hscript.FieldKind_KVar );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("KVar", new object[]{this.v});
		}
		
		
		public readonly object v;
		
	}
}


