// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Xml {
	public class Printer : global::Loreline.Internal.Lang.HxObject {
		
		public Printer(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public Printer(bool pretty) {
			global::Loreline.Internal.Xml.Printer.__hx_ctor_haxe_xml_Printer(this, pretty);
		}
		
		
		protected static void __hx_ctor_haxe_xml_Printer(global::Loreline.Internal.Xml.Printer __hx_this, bool pretty) {
			__hx_this.output = new global::Loreline.Internal.Root.StringBuf();
			__hx_this.pretty = pretty;
		}
		
		
		public static string print(global::Loreline.Internal.Root.Xml xml, global::Loreline.Internal.Lang.Null<bool> pretty) {
			global::Loreline.Internal.Lang.Null<bool> pretty1 = ( ( ! (pretty.hasValue) ) ? (new global::Loreline.Internal.Lang.Null<bool>(false, true)) : (pretty) );
			global::Loreline.Internal.Xml.Printer printer = new global::Loreline.Internal.Xml.Printer((pretty1).@value);
			printer.writeNode(xml, "");
			return printer.output.b.ToString();
		}
		
		
		public global::Loreline.Internal.Root.StringBuf output;
		
		public bool pretty;
		
		public virtual void writeNode(global::Loreline.Internal.Root.Xml @value, string tabs) {
			unchecked {
				switch (@value.nodeType) {
					case 0:
					{
						this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(global::Loreline.Internal.Lang.Runtime.concat(tabs, "<"))) ));
						{
							if (( @value.nodeType != global::Loreline.Internal.Root.Xml.Element )) {
								throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(@value.nodeType)))) );
							}
							
							this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(@value.nodeName)) ));
						}
						
						{
							object attribute = @value.attributes();
							while (global::Loreline.Internal.Lang.Runtime.toBool(global::Loreline.Internal.Lang.Runtime.callField(attribute, "hasNext", 407283053, null))) {
								string attribute1 = global::Loreline.Internal.Lang.Runtime.toString(global::Loreline.Internal.Lang.Runtime.callField(attribute, "next", 1224901875, null));
								this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(global::Loreline.Internal.Lang.Runtime.concat(global::Loreline.Internal.Lang.Runtime.concat(" ", attribute1), "=\""))) ));
								{
									string input = global::Loreline.Internal.Root.StringTools.htmlEscape(@value.@get(attribute1), new global::Loreline.Internal.Lang.Null<bool>(true, true));
									this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(input)) ));
								}
								
								this.output.b.Append(((string) ("\"") ));
							}
							
						}
						
						if (this.hasChildren(@value)) {
							this.output.b.Append(((string) (">") ));
							if (this.pretty) {
								this.output.b.Append(((string) ("\n") ));
							}
							
							{
								if (( ( @value.nodeType != global::Loreline.Internal.Root.Xml.Document ) && ( @value.nodeType != global::Loreline.Internal.Root.Xml.Element ) )) {
									throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element or Document but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(@value.nodeType)))) );
								}
								
								int _g_current = 0;
								global::Loreline.Internal.Root.Array<object> _g_array = @value.children;
								while (( _g_current < _g_array.length )) {
									global::Loreline.Internal.Root.Xml child = ((global::Loreline.Internal.Root.Xml) (_g_array[_g_current++]) );
									this.writeNode(child, ( (this.pretty) ? (global::Loreline.Internal.Lang.Runtime.concat(tabs, "\t")) : (tabs) ));
								}
								
							}
							
							this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(global::Loreline.Internal.Lang.Runtime.concat(tabs, "</"))) ));
							{
								if (( @value.nodeType != global::Loreline.Internal.Root.Xml.Element )) {
									throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(@value.nodeType)))) );
								}
								
								this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(@value.nodeName)) ));
							}
							
							this.output.b.Append(((string) (">") ));
							if (this.pretty) {
								this.output.b.Append(((string) ("\n") ));
							}
							
						}
						else {
							this.output.b.Append(((string) ("/>") ));
							if (this.pretty) {
								this.output.b.Append(((string) ("\n") ));
							}
							
						}
						
						break;
					}
					
					
					case 1:
					{
						if (( ( @value.nodeType == global::Loreline.Internal.Root.Xml.Document ) || ( @value.nodeType == global::Loreline.Internal.Root.Xml.Element ) )) {
							throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, unexpected ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(@value.nodeType)))) );
						}
						
						string nodeValue = @value.nodeValue;
						if (( nodeValue.Length != 0 )) {
							{
								string input1 = global::Loreline.Internal.Lang.Runtime.concat(tabs, global::Loreline.Internal.Root.StringTools.htmlEscape(nodeValue, default(global::Loreline.Internal.Lang.Null<bool>)));
								this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(input1)) ));
							}
							
							if (this.pretty) {
								this.output.b.Append(((string) ("\n") ));
							}
							
						}
						
						break;
					}
					
					
					case 2:
					{
						this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(global::Loreline.Internal.Lang.Runtime.concat(tabs, "<![CDATA["))) ));
						{
							if (( ( @value.nodeType == global::Loreline.Internal.Root.Xml.Document ) || ( @value.nodeType == global::Loreline.Internal.Root.Xml.Element ) )) {
								throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, unexpected ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(@value.nodeType)))) );
							}
							
							this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(@value.nodeValue)) ));
						}
						
						this.output.b.Append(((string) ("]]>") ));
						if (this.pretty) {
							this.output.b.Append(((string) ("\n") ));
						}
						
						break;
					}
					
					
					case 3:
					{
						if (( ( @value.nodeType == global::Loreline.Internal.Root.Xml.Document ) || ( @value.nodeType == global::Loreline.Internal.Root.Xml.Element ) )) {
							throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, unexpected ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(@value.nodeType)))) );
						}
						
						string commentContent = @value.nodeValue;
						commentContent = new global::Loreline.Internal.Root.EReg(((string) ("[\n\r\t]+") ), ((string) ("g") )).replace(commentContent, "");
						commentContent = global::Loreline.Internal.Lang.Runtime.concat(global::Loreline.Internal.Lang.Runtime.concat("<!--", commentContent), "-->");
						this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(tabs)) ));
						{
							string input2 = commentContent.Trim();
							this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(input2)) ));
						}
						
						if (this.pretty) {
							this.output.b.Append(((string) ("\n") ));
						}
						
						break;
					}
					
					
					case 4:
					{
						{
							if (( ( @value.nodeType == global::Loreline.Internal.Root.Xml.Document ) || ( @value.nodeType == global::Loreline.Internal.Root.Xml.Element ) )) {
								throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, unexpected ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(@value.nodeType)))) );
							}
							
							this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(global::Loreline.Internal.Lang.Runtime.concat(global::Loreline.Internal.Lang.Runtime.concat("<!DOCTYPE ", @value.nodeValue), ">"))) ));
						}
						
						if (this.pretty) {
							this.output.b.Append(((string) ("\n") ));
						}
						
						break;
					}
					
					
					case 5:
					{
						{
							if (( ( @value.nodeType == global::Loreline.Internal.Root.Xml.Document ) || ( @value.nodeType == global::Loreline.Internal.Root.Xml.Element ) )) {
								throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, unexpected ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(@value.nodeType)))) );
							}
							
							this.output.b.Append(((string) (global::Loreline.Internal.Root.Std.@string(global::Loreline.Internal.Lang.Runtime.concat(global::Loreline.Internal.Lang.Runtime.concat("<?", @value.nodeValue), "?>"))) ));
						}
						
						if (this.pretty) {
							this.output.b.Append(((string) ("\n") ));
						}
						
						break;
					}
					
					
					case 6:
					{
						if (( ( @value.nodeType != global::Loreline.Internal.Root.Xml.Document ) && ( @value.nodeType != global::Loreline.Internal.Root.Xml.Element ) )) {
							throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element or Document but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(@value.nodeType)))) );
						}
						
						int _g_current1 = 0;
						global::Loreline.Internal.Root.Array<object> _g_array1 = @value.children;
						while (( _g_current1 < _g_array1.length )) {
							global::Loreline.Internal.Root.Xml child1 = ((global::Loreline.Internal.Root.Xml) (_g_array1[_g_current1++]) );
							this.writeNode(child1, tabs);
						}
						
						break;
					}
					
					
				}
				
			}
		}
		
		
		public virtual bool hasChildren(global::Loreline.Internal.Root.Xml @value) {
			unchecked {
				{
					if (( ( @value.nodeType != global::Loreline.Internal.Root.Xml.Document ) && ( @value.nodeType != global::Loreline.Internal.Root.Xml.Element ) )) {
						throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element or Document but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(@value.nodeType)))) );
					}
					
					int _g_current = 0;
					global::Loreline.Internal.Root.Array<object> _g_array = @value.children;
					while (( _g_current < _g_array.length )) {
						global::Loreline.Internal.Root.Xml child = ((global::Loreline.Internal.Root.Xml) (_g_array[_g_current++]) );
						switch (child.nodeType) {
							case 0:
							case 1:
							{
								return true;
							}
							
							
							case 2:
							case 3:
							{
								if (( ( child.nodeType == global::Loreline.Internal.Root.Xml.Document ) || ( child.nodeType == global::Loreline.Internal.Root.Xml.Element ) )) {
									throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, unexpected ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(child.nodeType)))) );
								}
								
								if (( child.nodeValue.TrimStart().Length != 0 )) {
									return true;
								}
								
								break;
							}
							
							
							default:
							{
								break;
							}
							
						}
						
					}
					
				}
				
				return false;
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 784433846:
					{
						this.pretty = global::Loreline.Internal.Lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					case 209784577:
					{
						this.output = ((global::Loreline.Internal.Root.StringBuf) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1126235833:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "hasChildren", 1126235833)) );
					}
					
					
					case 1371405953:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "writeNode", 1371405953)) );
					}
					
					
					case 784433846:
					{
						return this.pretty;
					}
					
					
					case 209784577:
					{
						return this.output;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 1126235833:
					{
						return this.hasChildren(((global::Loreline.Internal.Root.Xml) (dynargs[0]) ));
					}
					
					
					case 1371405953:
					{
						this.writeNode(((global::Loreline.Internal.Root.Xml) (dynargs[0]) ), global::Loreline.Internal.Lang.Runtime.toString(dynargs[1]));
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("pretty");
			baseArr.push("output");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


