// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Root {
	public sealed class EReg : global::Loreline.Internal.Lang.HxObject {
		
		public EReg(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public EReg(string r, string opt) {
			global::Loreline.Internal.Root.EReg.__hx_ctor__EReg(this, r, opt);
		}
		
		
		private static void __hx_ctor__EReg(global::Loreline.Internal.Root.EReg __hx_this, string r, string opt) {
			unchecked {
				int opts = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(((object) (global::System.Text.RegularExpressions.RegexOptions.CultureInvariant) ))) );
				{
					int _g = 0;
					int _g1 = opt.Length;
					while (( _g < _g1 )) {
						int i = _g++;
						switch (((int) (opt[i]) )) {
							case 99:
							{
								opts |= ((int) (global::Loreline.Internal.Lang.Runtime.toInt(((object) (global::System.Text.RegularExpressions.RegexOptions.Compiled) ))) );
								break;
							}
							
							
							case 103:
							{
								__hx_this.isGlobal = true;
								break;
							}
							
							
							case 105:
							{
								opts |= ((int) (global::Loreline.Internal.Lang.Runtime.toInt(((object) (global::System.Text.RegularExpressions.RegexOptions.IgnoreCase) ))) );
								break;
							}
							
							
							case 109:
							{
								opts |= ((int) (global::Loreline.Internal.Lang.Runtime.toInt(((object) (global::System.Text.RegularExpressions.RegexOptions.Multiline) ))) );
								break;
							}
							
							
						}
						
					}
					
				}
				
				__hx_this.regex = new global::System.Text.RegularExpressions.Regex(((string) (r) ), ((global::System.Text.RegularExpressions.RegexOptions) (((object) (opts) )) ));
			}
		}
		
		
		public global::System.Text.RegularExpressions.Regex regex;
		
		public bool isGlobal;
		
		public string replace(string s, string @by) {
			unchecked {
				if (this.isGlobal) {
					return this.regex.Replace(((string) (s) ), ((string) (@by) ));
				}
				else {
					return this.regex.Replace(((string) (s) ), ((string) (@by) ), ((int) (1) ));
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1821933:
					{
						this.isGlobal = global::Loreline.Internal.Lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					case 1723805383:
					{
						this.regex = ((global::System.Text.RegularExpressions.Regex) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 724060212:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "replace", 724060212)) );
					}
					
					
					case 1821933:
					{
						return this.isGlobal;
					}
					
					
					case 1723805383:
					{
						return this.regex;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 724060212:
					{
						return this.replace(global::Loreline.Internal.Lang.Runtime.toString(dynargs[0]), global::Loreline.Internal.Lang.Runtime.toString(dynargs[1]));
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("isGlobal");
			baseArr.push("regex");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


