// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Root._Xml {
	public sealed class XmlType_Impl_ {
		
		public static string toString(int this1) {
			unchecked {
				switch (((int) (this1) )) {
					case 0:
					{
						return "Element";
					}
					
					
					case 1:
					{
						return "PCData";
					}
					
					
					case 2:
					{
						return "CData";
					}
					
					
					case 3:
					{
						return "Comment";
					}
					
					
					case 4:
					{
						return "DocType";
					}
					
					
					case 5:
					{
						return "ProcessingInstruction";
					}
					
					
					case 6:
					{
						return "Document";
					}
					
					
				}
				
				return null;
			}
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Root {
	public class Xml : global::Loreline.Internal.Lang.HxObject {
		
		static Xml() {
			unchecked{
				global::Loreline.Internal.Root.Xml.Element = ((int) (0) );
				global::Loreline.Internal.Root.Xml.PCData = ((int) (1) );
				global::Loreline.Internal.Root.Xml.CData = ((int) (2) );
				global::Loreline.Internal.Root.Xml.Document = ((int) (6) );
			}
		}
		
		
		public Xml(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public Xml(int nodeType) {
			global::Loreline.Internal.Root.Xml.__hx_ctor__Xml(this, nodeType);
		}
		
		
		protected static void __hx_ctor__Xml(global::Loreline.Internal.Root.Xml __hx_this, int nodeType) {
			__hx_this.nodeType = nodeType;
			__hx_this.children = new global::Loreline.Internal.Root.Array<object>(new object[]{});
			__hx_this.attributeMap = new global::Loreline.Internal.Ds.StringMap<string>();
		}
		
		
		public static int Element;
		
		public static int PCData;
		
		public static int CData;
		
		public static int Document;
		
		public int nodeType;
		
		public string nodeName;
		
		public string nodeValue;
		
		public global::Loreline.Internal.Root.Array<object> children;
		
		public global::Loreline.Internal.Ds.StringMap<string> attributeMap;
		
		public virtual string @get(string att) {
			if (( this.nodeType != global::Loreline.Internal.Root.Xml.Element )) {
				throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(this.nodeType)))) );
			}
			
			return global::Loreline.Internal.Lang.Runtime.toString((((global::Loreline.Internal.Ds.StringMap<string>) (global::Loreline.Internal.Ds.StringMap<object>.__hx_cast<string>(((global::Loreline.Internal.Ds.StringMap) (((global::Loreline.Internal.IMap<string, string>) (this.attributeMap) )) ))) ).@get(att)).toDynamic());
		}
		
		
		public virtual bool exists(string att) {
			if (( this.nodeType != global::Loreline.Internal.Root.Xml.Element )) {
				throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(this.nodeType)))) );
			}
			
			return ((global::Loreline.Internal.Ds.StringMap<string>) (global::Loreline.Internal.Ds.StringMap<object>.__hx_cast<string>(((global::Loreline.Internal.Ds.StringMap) (((global::Loreline.Internal.IMap<string, string>) (this.attributeMap) )) ))) ).exists(att);
		}
		
		
		public virtual object attributes() {
			if (( this.nodeType != global::Loreline.Internal.Root.Xml.Element )) {
				throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(this.nodeType)))) );
			}
			
			return ((object) (new global::Loreline.Internal.Ds._StringMap.StringMapKeyIterator<string>(((global::Loreline.Internal.Ds.StringMap<string>) (global::Loreline.Internal.Ds.StringMap<object>.__hx_cast<string>(((global::Loreline.Internal.Ds.StringMap) (((global::Loreline.Internal.IMap<string, string>) (this.attributeMap) )) ))) ))) );
		}
		
		
		public virtual object elements() {
			if (( ( this.nodeType != global::Loreline.Internal.Root.Xml.Document ) && ( this.nodeType != global::Loreline.Internal.Root.Xml.Element ) )) {
				throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element or Document but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(this.nodeType)))) );
			}
			
			global::Loreline.Internal.Root.Array<object> _g = new global::Loreline.Internal.Root.Array<object>(new object[]{});
			{
				int _g1 = 0;
				global::Loreline.Internal.Root.Array<object> _g2 = this.children;
				while (( _g1 < _g2.length )) {
					global::Loreline.Internal.Root.Xml child = ((global::Loreline.Internal.Root.Xml) (_g2[_g1]) );
					 ++ _g1;
					if (( child.nodeType == global::Loreline.Internal.Root.Xml.Element )) {
						_g.push(child);
					}
					
				}
				
			}
			
			global::Loreline.Internal.Root.Array<object> ret = _g;
			return new global::Loreline.Internal.Iterators.ArrayIterator<object>(((global::Loreline.Internal.Root.Array<object>) (ret) ));
		}
		
		
		public virtual object elementsNamed(string name) {
			if (( ( this.nodeType != global::Loreline.Internal.Root.Xml.Document ) && ( this.nodeType != global::Loreline.Internal.Root.Xml.Element ) )) {
				throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element or Document but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(this.nodeType)))) );
			}
			
			global::Loreline.Internal.Root.Array<object> _g = new global::Loreline.Internal.Root.Array<object>(new object[]{});
			{
				int _g1 = 0;
				global::Loreline.Internal.Root.Array<object> _g2 = this.children;
				while (( _g1 < _g2.length )) {
					global::Loreline.Internal.Root.Xml child = ((global::Loreline.Internal.Root.Xml) (_g2[_g1]) );
					 ++ _g1;
					bool tmp = default(bool);
					if (( child.nodeType == global::Loreline.Internal.Root.Xml.Element )) {
						if (( child.nodeType != global::Loreline.Internal.Root.Xml.Element )) {
							throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(child.nodeType)))) );
						}
						
						tmp = ( child.nodeName == name );
					}
					else {
						tmp = false;
					}
					
					if (tmp) {
						_g.push(child);
					}
					
				}
				
			}
			
			global::Loreline.Internal.Root.Array<object> ret = _g;
			return new global::Loreline.Internal.Iterators.ArrayIterator<object>(((global::Loreline.Internal.Root.Array<object>) (ret) ));
		}
		
		
		public virtual global::Loreline.Internal.Root.Xml firstElement() {
			if (( ( this.nodeType != global::Loreline.Internal.Root.Xml.Document ) && ( this.nodeType != global::Loreline.Internal.Root.Xml.Element ) )) {
				throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat("Bad node type, expected Element or Document but found ", global::Loreline.Internal.Root._Xml.XmlType_Impl_.toString(this.nodeType)))) );
			}
			
			{
				int _g = 0;
				global::Loreline.Internal.Root.Array<object> _g1 = this.children;
				while (( _g < _g1.length )) {
					global::Loreline.Internal.Root.Xml child = ((global::Loreline.Internal.Root.Xml) (_g1[_g]) );
					 ++ _g;
					if (( child.nodeType == global::Loreline.Internal.Root.Xml.Element )) {
						return child;
					}
					
				}
				
			}
			
			return null;
		}
		
		
		public string toString() {
			return global::Loreline.Internal.Xml.Printer.print(this, default(global::Loreline.Internal.Lang.Null<bool>));
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1988514268:
					{
						this.nodeType = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 364006368:
					{
						this.attributeMap = ((global::Loreline.Internal.Ds.StringMap<string>) (global::Loreline.Internal.Ds.StringMap<object>.__hx_cast<string>(((global::Loreline.Internal.Ds.StringMap) (@value) ))) );
						return @value;
					}
					
					
					case 1886001471:
					{
						this.children = ((global::Loreline.Internal.Root.Array<object>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<object>(((global::Loreline.Internal.Root.Array) (@value) ))) );
						return @value;
					}
					
					
					case 1441685007:
					{
						this.nodeValue = global::Loreline.Internal.Lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 1920782701:
					{
						this.nodeName = global::Loreline.Internal.Lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 1988514268:
					{
						this.nodeType = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 946786476:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 798803052:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "firstElement", 798803052)) );
					}
					
					
					case 1116398082:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "elementsNamed", 1116398082)) );
					}
					
					
					case 63190583:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "elements", 63190583)) );
					}
					
					
					case 393324759:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "attributes", 393324759)) );
					}
					
					
					case 1071652316:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "exists", 1071652316)) );
					}
					
					
					case 5144726:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 364006368:
					{
						return this.attributeMap;
					}
					
					
					case 1886001471:
					{
						return this.children;
					}
					
					
					case 1441685007:
					{
						return this.nodeValue;
					}
					
					
					case 1920782701:
					{
						return this.nodeName;
					}
					
					
					case 1988514268:
					{
						return this.nodeType;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1988514268:
					{
						return ((double) (this.nodeType) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 946786476:
					{
						return this.toString();
					}
					
					
					case 798803052:
					{
						return this.firstElement();
					}
					
					
					case 1116398082:
					{
						return this.elementsNamed(global::Loreline.Internal.Lang.Runtime.toString(dynargs[0]));
					}
					
					
					case 63190583:
					{
						return this.elements();
					}
					
					
					case 393324759:
					{
						return this.attributes();
					}
					
					
					case 1071652316:
					{
						return this.exists(global::Loreline.Internal.Lang.Runtime.toString(dynargs[0]));
					}
					
					
					case 5144726:
					{
						return this.@get(global::Loreline.Internal.Lang.Runtime.toString(dynargs[0]));
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("attributeMap");
			baseArr.push("children");
			baseArr.push("nodeValue");
			baseArr.push("nodeName");
			baseArr.push("nodeType");
			base.__hx_getFields(baseArr);
		}
		
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}


