// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Ds {
	public class BalancedTree<K, V> : global::Loreline.Internal.Lang.HxObject, global::Loreline.Internal.Ds.BalancedTree, global::Loreline.Internal.IMap<K, V> {
		
		public BalancedTree(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public BalancedTree() {
			global::Loreline.Internal.Ds.BalancedTree<object, object>.__hx_ctor_haxe_ds_BalancedTree<K, V>(((global::Loreline.Internal.Ds.BalancedTree<K, V>) (this) ));
		}
		
		
		protected static void __hx_ctor_haxe_ds_BalancedTree<K_c, V_c>(global::Loreline.Internal.Ds.BalancedTree<K_c, V_c> __hx_this) {
		}
		
		
		public static object __hx_cast<K_c_c, V_c_c>(global::Loreline.Internal.Ds.BalancedTree me) {
			return ( (( me != null )) ? (me.haxe_ds_BalancedTree_cast<K_c_c, V_c_c>()) : default(object) );
		}
		
		
		public virtual object haxe_ds_BalancedTree_cast<K_c, V_c>() {
			if (( global::Loreline.Internal.Lang.Runtime.eq(typeof(K), typeof(K_c)) && global::Loreline.Internal.Lang.Runtime.eq(typeof(V), typeof(V_c)) )) {
				return this;
			}
			
			global::Loreline.Internal.Ds.BalancedTree<K_c, V_c> new_me = new global::Loreline.Internal.Ds.BalancedTree<K_c, V_c>(global::Loreline.Internal.Lang.EmptyObject.EMPTY);
			global::Loreline.Internal.Root.Array<string> fields = global::Loreline.Internal.Root.Reflect.fields(this);
			int i = 0;
			while (( i < fields.length )) {
				string field = fields[i++];
				global::Loreline.Internal.Root.Reflect.setField(new_me, field, global::Loreline.Internal.Root.Reflect.field(this, field));
			}
			
			return new_me;
		}
		
		
		public virtual object haxe_IMap_cast<K_c, V_c>() {
			return this.haxe_ds_BalancedTree_cast<K, V>();
		}
		
		
		public global::Loreline.Internal.Ds.TreeNode<K, V> root;
		
		public virtual void @set(K key, V @value) {
			this.root = this.setLoop(key, @value, this.root);
		}
		
		
		public virtual global::Loreline.Internal.Lang.Null<V> @get(K key) {
			global::Loreline.Internal.Ds.TreeNode<K, V> node = this.root;
			while (( node != null )) {
				int c = this.compare(key, node.key);
				if (( c == 0 )) {
					return new global::Loreline.Internal.Lang.Null<V>(node.@value, true);
				}
				
				if (( c < 0 )) {
					node = node.left;
				}
				else {
					node = node.right;
				}
				
			}
			
			return default(global::Loreline.Internal.Lang.Null<V>);
		}
		
		
		public virtual object keys() {
			global::Loreline.Internal.Root.Array<K> ret = new global::Loreline.Internal.Root.Array<K>(new K[]{});
			this.keysLoop(this.root, ret);
			return new global::Loreline.Internal.Iterators.ArrayIterator<K>(((global::Loreline.Internal.Root.Array<K>) (ret) ));
		}
		
		
		public virtual global::Loreline.Internal.Ds.TreeNode<K, V> setLoop(K k, V v, global::Loreline.Internal.Ds.TreeNode<K, V> node) {
			if (( node == null )) {
				return new global::Loreline.Internal.Ds.TreeNode<K, V>(default(global::Loreline.Internal.Ds.TreeNode<K, V>), global::Loreline.Internal.Lang.Runtime.genericCast<K>(k), global::Loreline.Internal.Lang.Runtime.genericCast<V>(v), default(global::Loreline.Internal.Ds.TreeNode<K, V>), default(global::Loreline.Internal.Lang.Null<int>));
			}
			
			int c = this.compare(k, node.key);
			if (( c == 0 )) {
				return new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (node.left) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(k), global::Loreline.Internal.Lang.Runtime.genericCast<V>(v), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (node.right) ), new global::Loreline.Internal.Lang.Null<int>(( (( node == null )) ? (0) : (node._height) ), true));
			}
			else if (( c < 0 )) {
				global::Loreline.Internal.Ds.TreeNode<K, V> nl = this.setLoop(k, v, node.left);
				return this.balance(nl, node.key, node.@value, node.right);
			}
			else {
				global::Loreline.Internal.Ds.TreeNode<K, V> nr = this.setLoop(k, v, node.right);
				return this.balance(node.left, node.key, node.@value, nr);
			}
			
		}
		
		
		public virtual void keysLoop(global::Loreline.Internal.Ds.TreeNode<K, V> node, global::Loreline.Internal.Root.Array<K> acc) {
			if (( node != null )) {
				this.keysLoop(node.left, acc);
				acc.push(node.key);
				this.keysLoop(node.right, acc);
			}
			
		}
		
		
		public virtual global::Loreline.Internal.Ds.TreeNode<K, V> balance(global::Loreline.Internal.Ds.TreeNode<K, V> l, K k, V v, global::Loreline.Internal.Ds.TreeNode<K, V> r) {
			unchecked {
				int hl = ( (( l == null )) ? (0) : (l._height) );
				int hr = ( (( r == null )) ? (0) : (r._height) );
				if (( hl > ( hr + 2 ) )) {
					global::Loreline.Internal.Ds.TreeNode<K, V> _this = l.left;
					global::Loreline.Internal.Ds.TreeNode<K, V> _this1 = l.right;
					if (( (( (( _this == null )) ? (0) : (_this._height) )) >= (( (( _this1 == null )) ? (0) : (_this1._height) )) )) {
						return new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (l.left) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(l.key), global::Loreline.Internal.Lang.Runtime.genericCast<V>(l.@value), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (l.right) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(k), global::Loreline.Internal.Lang.Runtime.genericCast<V>(v), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (r) ), default(global::Loreline.Internal.Lang.Null<int>))) ), default(global::Loreline.Internal.Lang.Null<int>));
					}
					else {
						return new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (l.left) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(l.key), global::Loreline.Internal.Lang.Runtime.genericCast<V>(l.@value), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (l.right.left) ), default(global::Loreline.Internal.Lang.Null<int>))) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(l.right.key), global::Loreline.Internal.Lang.Runtime.genericCast<V>(l.right.@value), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (l.right.right) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(k), global::Loreline.Internal.Lang.Runtime.genericCast<V>(v), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (r) ), default(global::Loreline.Internal.Lang.Null<int>))) ), default(global::Loreline.Internal.Lang.Null<int>));
					}
					
				}
				else if (( hr > ( hl + 2 ) )) {
					global::Loreline.Internal.Ds.TreeNode<K, V> _this2 = r.right;
					global::Loreline.Internal.Ds.TreeNode<K, V> _this3 = r.left;
					if (( (( (( _this2 == null )) ? (0) : (_this2._height) )) > (( (( _this3 == null )) ? (0) : (_this3._height) )) )) {
						return new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (l) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(k), global::Loreline.Internal.Lang.Runtime.genericCast<V>(v), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (r.left) ), default(global::Loreline.Internal.Lang.Null<int>))) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(r.key), global::Loreline.Internal.Lang.Runtime.genericCast<V>(r.@value), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (r.right) ), default(global::Loreline.Internal.Lang.Null<int>));
					}
					else {
						return new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (l) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(k), global::Loreline.Internal.Lang.Runtime.genericCast<V>(v), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (r.left.left) ), default(global::Loreline.Internal.Lang.Null<int>))) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(r.left.key), global::Loreline.Internal.Lang.Runtime.genericCast<V>(r.left.@value), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (r.left.right) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(r.key), global::Loreline.Internal.Lang.Runtime.genericCast<V>(r.@value), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (r.right) ), default(global::Loreline.Internal.Lang.Null<int>))) ), default(global::Loreline.Internal.Lang.Null<int>));
					}
					
				}
				else {
					return new global::Loreline.Internal.Ds.TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (l) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(k), global::Loreline.Internal.Lang.Runtime.genericCast<V>(v), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (r) ), new global::Loreline.Internal.Lang.Null<int>(( (( (( hl > hr )) ? (hl) : (hr) )) + 1 ), true));
				}
				
			}
		}
		
		
		public virtual int compare(K k1, K k2) {
			return global::Loreline.Internal.Root.Reflect.compare<K>(global::Loreline.Internal.Lang.Runtime.genericCast<K>(k1), global::Loreline.Internal.Lang.Runtime.genericCast<K>(k2));
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1269755426:
					{
						this.root = ((global::Loreline.Internal.Ds.TreeNode<K, V>) (global::Loreline.Internal.Ds.TreeNode<object, object>.__hx_cast<K, V>(((global::Loreline.Internal.Ds.TreeNode) (@value) ))) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 57219237:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "compare", 57219237)) );
					}
					
					
					case 596483356:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "balance", 596483356)) );
					}
					
					
					case 451001976:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "keysLoop", 451001976)) );
					}
					
					
					case 222029606:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "setLoop", 222029606)) );
					}
					
					
					case 1191633396:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "keys", 1191633396)) );
					}
					
					
					case 5144726:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 5741474:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "set", 5741474)) );
					}
					
					
					case 1269755426:
					{
						return this.root;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 57219237:
					{
						return this.compare(global::Loreline.Internal.Lang.Runtime.genericCast<K>(dynargs[0]), global::Loreline.Internal.Lang.Runtime.genericCast<K>(dynargs[1]));
					}
					
					
					case 596483356:
					{
						return this.balance(((global::Loreline.Internal.Ds.TreeNode<K, V>) (global::Loreline.Internal.Ds.TreeNode<object, object>.__hx_cast<K, V>(((global::Loreline.Internal.Ds.TreeNode) (dynargs[0]) ))) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(dynargs[1]), global::Loreline.Internal.Lang.Runtime.genericCast<V>(dynargs[2]), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (global::Loreline.Internal.Ds.TreeNode<object, object>.__hx_cast<K, V>(((global::Loreline.Internal.Ds.TreeNode) (dynargs[3]) ))) ));
					}
					
					
					case 451001976:
					{
						this.keysLoop(((global::Loreline.Internal.Ds.TreeNode<K, V>) (global::Loreline.Internal.Ds.TreeNode<object, object>.__hx_cast<K, V>(((global::Loreline.Internal.Ds.TreeNode) (dynargs[0]) ))) ), ((global::Loreline.Internal.Root.Array<K>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<K>(((global::Loreline.Internal.Root.Array) (dynargs[1]) ))) ));
						break;
					}
					
					
					case 222029606:
					{
						return this.setLoop(global::Loreline.Internal.Lang.Runtime.genericCast<K>(dynargs[0]), global::Loreline.Internal.Lang.Runtime.genericCast<V>(dynargs[1]), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (global::Loreline.Internal.Ds.TreeNode<object, object>.__hx_cast<K, V>(((global::Loreline.Internal.Ds.TreeNode) (dynargs[2]) ))) ));
					}
					
					
					case 1191633396:
					{
						return this.keys();
					}
					
					
					case 5144726:
					{
						return (this.@get(global::Loreline.Internal.Lang.Runtime.genericCast<K>(dynargs[0]))).toDynamic();
					}
					
					
					case 5741474:
					{
						this.@set(global::Loreline.Internal.Lang.Runtime.genericCast<K>(dynargs[0]), global::Loreline.Internal.Lang.Runtime.genericCast<V>(dynargs[1]));
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("root");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Ds {
	[global::Loreline.Internal.Lang.GenericInterface(typeof(global::Loreline.Internal.Ds.BalancedTree<object, object>))]
	public interface BalancedTree : global::Loreline.Internal.Lang.IHxObject, global::Loreline.Internal.Lang.IGenericObject {
		
		object haxe_ds_BalancedTree_cast<K_c, V_c>();
		
		object haxe_IMap_cast<K_c, V_c>();
		
		object keys();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Ds {
	public class TreeNode<K, V> : global::Loreline.Internal.Lang.HxObject, global::Loreline.Internal.Ds.TreeNode {
		
		public TreeNode(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public TreeNode(global::Loreline.Internal.Ds.TreeNode<K, V> l, K k, V v, global::Loreline.Internal.Ds.TreeNode<K, V> r, global::Loreline.Internal.Lang.Null<int> h) {
			global::Loreline.Internal.Ds.TreeNode<object, object>.__hx_ctor_haxe_ds_TreeNode<K, V>(((global::Loreline.Internal.Ds.TreeNode<K, V>) (this) ), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (l) ), global::Loreline.Internal.Lang.Runtime.genericCast<K>(k), global::Loreline.Internal.Lang.Runtime.genericCast<V>(v), ((global::Loreline.Internal.Ds.TreeNode<K, V>) (r) ), ((global::Loreline.Internal.Lang.Null<int>) (h) ));
		}
		
		
		protected static void __hx_ctor_haxe_ds_TreeNode<K_c, V_c>(global::Loreline.Internal.Ds.TreeNode<K_c, V_c> __hx_this, global::Loreline.Internal.Ds.TreeNode<K_c, V_c> l, K_c k, V_c v, global::Loreline.Internal.Ds.TreeNode<K_c, V_c> r, global::Loreline.Internal.Lang.Null<int> h) {
			unchecked {
				int h1 = ( ( ! (h.hasValue) ) ? (-1) : ((h).@value) );
				__hx_this.left = l;
				__hx_this.key = k;
				__hx_this.@value = v;
				__hx_this.right = r;
				if (( h1 == -1 )) {
					int tmp = default(int);
					global::Loreline.Internal.Ds.TreeNode<K_c, V_c> _this = __hx_this.left;
					global::Loreline.Internal.Ds.TreeNode<K_c, V_c> _this1 = __hx_this.right;
					if (( (( (( _this == null )) ? (0) : (_this._height) )) > (( (( _this1 == null )) ? (0) : (_this1._height) )) )) {
						global::Loreline.Internal.Ds.TreeNode<K_c, V_c> _this2 = __hx_this.left;
						tmp = ( (( _this2 == null )) ? (0) : (_this2._height) );
					}
					else {
						global::Loreline.Internal.Ds.TreeNode<K_c, V_c> _this3 = __hx_this.right;
						tmp = ( (( _this3 == null )) ? (0) : (_this3._height) );
					}
					
					__hx_this._height = ( tmp + 1 );
				}
				else {
					__hx_this._height = h1;
				}
				
			}
		}
		
		
		public static object __hx_cast<K_c_c, V_c_c>(global::Loreline.Internal.Ds.TreeNode me) {
			return ( (( me != null )) ? (me.haxe_ds_TreeNode_cast<K_c_c, V_c_c>()) : default(object) );
		}
		
		
		public virtual object haxe_ds_TreeNode_cast<K_c, V_c>() {
			if (( global::Loreline.Internal.Lang.Runtime.eq(typeof(K), typeof(K_c)) && global::Loreline.Internal.Lang.Runtime.eq(typeof(V), typeof(V_c)) )) {
				return this;
			}
			
			global::Loreline.Internal.Ds.TreeNode<K_c, V_c> new_me = new global::Loreline.Internal.Ds.TreeNode<K_c, V_c>(global::Loreline.Internal.Lang.EmptyObject.EMPTY);
			global::Loreline.Internal.Root.Array<string> fields = global::Loreline.Internal.Root.Reflect.fields(this);
			int i = 0;
			while (( i < fields.length )) {
				string field = fields[i++];
				global::Loreline.Internal.Root.Reflect.setField(new_me, field, global::Loreline.Internal.Root.Reflect.field(this, field));
			}
			
			return new_me;
		}
		
		
		public global::Loreline.Internal.Ds.TreeNode<K, V> left;
		
		public global::Loreline.Internal.Ds.TreeNode<K, V> right;
		
		public K key;
		
		public V @value;
		
		public int _height;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1891834246:
					{
						this._height = ((int) (@value) );
						return @value;
					}
					
					
					case 834174833:
					{
						this.@value = global::Loreline.Internal.Lang.Runtime.genericCast<V>(((object) (@value) ));
						return ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(((object) (@value) ))) );
					}
					
					
					case 5343647:
					{
						this.key = global::Loreline.Internal.Lang.Runtime.genericCast<K>(((object) (@value) ));
						return ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(((object) (@value) ))) );
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1891834246:
					{
						this._height = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 834174833:
					{
						this.@value = global::Loreline.Internal.Lang.Runtime.genericCast<V>(@value);
						return @value;
					}
					
					
					case 5343647:
					{
						this.key = global::Loreline.Internal.Lang.Runtime.genericCast<K>(@value);
						return @value;
					}
					
					
					case 1768164316:
					{
						this.right = ((global::Loreline.Internal.Ds.TreeNode<K, V>) (global::Loreline.Internal.Ds.TreeNode<object, object>.__hx_cast<K, V>(((global::Loreline.Internal.Ds.TreeNode) (@value) ))) );
						return @value;
					}
					
					
					case 1202718727:
					{
						this.left = ((global::Loreline.Internal.Ds.TreeNode<K, V>) (global::Loreline.Internal.Ds.TreeNode<object, object>.__hx_cast<K, V>(((global::Loreline.Internal.Ds.TreeNode) (@value) ))) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1891834246:
					{
						return this._height;
					}
					
					
					case 834174833:
					{
						return this.@value;
					}
					
					
					case 5343647:
					{
						return this.key;
					}
					
					
					case 1768164316:
					{
						return this.right;
					}
					
					
					case 1202718727:
					{
						return this.left;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1891834246:
					{
						return ((double) (this._height) );
					}
					
					
					case 834174833:
					{
						return ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(((object) (this.@value) ))) );
					}
					
					
					case 5343647:
					{
						return ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(((object) (this.key) ))) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("_height");
			baseArr.push("value");
			baseArr.push("key");
			baseArr.push("right");
			baseArr.push("left");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Ds {
	[global::Loreline.Internal.Lang.GenericInterface(typeof(global::Loreline.Internal.Ds.TreeNode<object, object>))]
	public interface TreeNode : global::Loreline.Internal.Lang.IHxObject, global::Loreline.Internal.Lang.IGenericObject {
		
		object haxe_ds_TreeNode_cast<K_c, V_c>();
		
	}
}


