// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal {
	public class StackItem : global::Loreline.Internal.Lang.Enum {
		
		protected StackItem(int index) : base(index) {
		}
		
		
		public static readonly global::Loreline.Internal.StackItem CFunction = new global::Loreline.Internal.StackItem_CFunction();
		
		public static global::Loreline.Internal.StackItem Module(string m) {
			return new global::Loreline.Internal.StackItem_Module(m);
		}
		
		
		public static global::Loreline.Internal.StackItem FilePos(global::Loreline.Internal.StackItem s, string file, int line, object column) {
			return new global::Loreline.Internal.StackItem_FilePos(s, file, line, column);
		}
		
		
		public static global::Loreline.Internal.StackItem Method(string classname, string method) {
			return new global::Loreline.Internal.StackItem_Method(classname, method);
		}
		
		
		public static global::Loreline.Internal.StackItem LocalFunction(object v) {
			return new global::Loreline.Internal.StackItem_LocalFunction(v);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal {
	public sealed class StackItem_CFunction : global::Loreline.Internal.StackItem {
		
		public StackItem_CFunction() : base(0) {
		}
		
		
		public override string getTag() {
			return "CFunction";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal {
	public sealed class StackItem_Module : global::Loreline.Internal.StackItem {
		
		public StackItem_Module(string m) : base(1) {
			this.m = m;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.m});
		}
		
		
		public override string getTag() {
			return "Module";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(1, new object[]{this.m});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.StackItem_Module en = ( other as global::Loreline.Internal.StackItem_Module );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.m) ), ((object) (en.m) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("Module", new object[]{this.m});
		}
		
		
		public readonly string m;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal {
	public sealed class StackItem_FilePos : global::Loreline.Internal.StackItem {
		
		public StackItem_FilePos(global::Loreline.Internal.StackItem s, string file, int line, object column) : base(2) {
			this.s = s;
			this.file = file;
			this.line = line;
			this.column = column;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.s, this.file, this.line, this.column});
		}
		
		
		public override string getTag() {
			return "FilePos";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(2, new object[]{this.s, this.file, this.line, this.column});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.StackItem_FilePos en = ( other as global::Loreline.Internal.StackItem_FilePos );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.s) ), ((object) (en.s) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.file) ), ((object) (en.file) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.line) ), ((object) (en.line) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.column) ), ((object) (en.column) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("FilePos", new object[]{this.s, this.file, this.line, this.column});
		}
		
		
		public readonly global::Loreline.Internal.StackItem s;
		
		public readonly string file;
		
		public readonly int line;
		
		public readonly object column;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal {
	public sealed class StackItem_Method : global::Loreline.Internal.StackItem {
		
		public StackItem_Method(string classname, string method) : base(3) {
			this.classname = classname;
			this.method = method;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.classname, this.method});
		}
		
		
		public override string getTag() {
			return "Method";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(3, new object[]{this.classname, this.method});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.StackItem_Method en = ( other as global::Loreline.Internal.StackItem_Method );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.classname) ), ((object) (en.classname) ))) ) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.method) ), ((object) (en.method) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("Method", new object[]{this.classname, this.method});
		}
		
		
		public readonly string classname;
		
		public readonly string method;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal {
	public sealed class StackItem_LocalFunction : global::Loreline.Internal.StackItem {
		
		public StackItem_LocalFunction(object v) : base(4) {
			this.v = v;
		}
		
		
		public override global::Loreline.Internal.Root.Array getParams() {
			return new global::Loreline.Internal.Root.Array(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "LocalFunction";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::Loreline.Internal.Lang.Enum.paramsGetHashCode(4, new object[]{this.v});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::Loreline.Internal.StackItem_LocalFunction en = ( other as global::Loreline.Internal.StackItem_LocalFunction );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Loreline.Internal.Root.Type.enumEq(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::Loreline.Internal.Lang.Enum.paramsToString("LocalFunction", new object[]{this.v});
		}
		
		
		public readonly object v;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal._CallStack {
	public sealed class CallStack_Impl_ {
		
		public static global::Loreline.Internal.Root.Array callStack() {
			unchecked {
				return global::Loreline.Internal.NativeStackTrace.toHaxe(new global::System.Diagnostics.StackTrace(((int) (1) ), ((bool) (true) )), null);
			}
		}
		
		
	}
}


