// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Cs {
	public class Lib : global::Loreline.Internal.Lang.HxObject {
		
		public Lib(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public Lib() {
			global::Loreline.Internal.Cs.Lib.__hx_ctor_cs_Lib(this);
		}
		
		
		protected static void __hx_ctor_cs_Lib(global::Loreline.Internal.Cs.Lib __hx_this) {
		}
		
		
		public static string decimalSeparator;
		
		public static void applyCultureChanges() {
			global::System.Globalization.CultureInfo ci = new global::System.Globalization.CultureInfo(((string) (global::System.Threading.Thread.CurrentThread.CurrentCulture.Name) ), ((bool) (true) ));
			global::Loreline.Internal.Cs.Lib.decimalSeparator = ci.NumberFormat.NumberDecimalSeparator;
			ci.NumberFormat.NumberDecimalSeparator = ((string) (".") );
			global::System.Threading.Thread.CurrentThread.CurrentCulture = ((global::System.Globalization.CultureInfo) (ci) );
		}
		
		
		public static void p_nativeArray<T>(global::Loreline.Internal.Root.Array<T> arr, global::System.Array ret) {
			T[] native = arr.__a;
			int len = arr.length;
			global::System.Array.Copy(((global::System.Array) (native) ), ((int) (0) ), ((global::System.Array) (ret) ), ((int) (0) ), ((int) (len) ));
		}
		
		
	}
}


