// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Root {
	public class Sys : global::Loreline.Internal.Lang.HxObject {
		
		public Sys(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public Sys() {
			global::Loreline.Internal.Root.Sys.__hx_ctor__Sys(this);
		}
		
		
		protected static void __hx_ctor__Sys(global::Loreline.Internal.Root.Sys __hx_this) {
		}
		
		
		public static readonly long epochTicks = new global::System.DateTime(((int) (1970) ), ((int) (1) ), ((int) (1) )).Ticks;
		
		public static double time() {
			return ( ((double) (((long) (( ((long) (global::System.DateTime.UtcNow.Ticks) ) - ((long) (global::Loreline.Internal.Root.Sys.epochTicks) ) )) )) ) / ((double) (global::System.TimeSpan.TicksPerSecond) ) );
		}
		
		
	}
}


