// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Hscript {
	public class Tools : global::Loreline.Internal.Lang.HxObject {
		
		public Tools(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public Tools() {
			global::Loreline.Internal.Hscript.Tools.__hx_ctor_hscript_Tools(this);
		}
		
		
		protected static void __hx_ctor_hscript_Tools(global::Loreline.Internal.Hscript.Tools __hx_this) {
		}
		
		
		public static void iter(global::Loreline.Internal.Hscript.Expr e, global::Loreline.Internal.Lang.Function f) {
			unchecked {
				switch (e._hx_index) {
					case 0:
					{
						global::Loreline.Internal.Hscript.Const _g = ( e as global::Loreline.Internal.Hscript.Expr_EConst ).c;
						break;
					}
					
					
					case 1:
					{
						string _g1 = ( e as global::Loreline.Internal.Hscript.Expr_EIdent ).v;
						break;
					}
					
					
					case 2:
					{
						string _g2 = ( e as global::Loreline.Internal.Hscript.Expr_EVar ).n;
						global::Loreline.Internal.Hscript.CType _g3 = ( e as global::Loreline.Internal.Hscript.Expr_EVar ).t;
						{
							global::Loreline.Internal.Hscript.Expr e1 = ( e as global::Loreline.Internal.Hscript.Expr_EVar ).e;
							if (( e1 != null )) {
								f.__hx_invoke1_o(default(double), e1);
							}
							
						}
						
						break;
					}
					
					
					case 3:
					{
						global::Loreline.Internal.Hscript.Expr e2 = ( e as global::Loreline.Internal.Hscript.Expr_EParent ).e;
						f.__hx_invoke1_o(default(double), e2);
						break;
					}
					
					
					case 4:
					{
						global::Loreline.Internal.Root.Array<object> el = ( e as global::Loreline.Internal.Hscript.Expr_EBlock ).e;
						{
							int _g4 = 0;
							while (( _g4 < el.length )) {
								global::Loreline.Internal.Hscript.Expr e3 = ((global::Loreline.Internal.Hscript.Expr) (el[_g4]) );
								 ++ _g4;
								f.__hx_invoke1_o(default(double), e3);
							}
							
						}
						
						break;
					}
					
					
					case 5:
					{
						string _g5 = ( e as global::Loreline.Internal.Hscript.Expr_EField ).f;
						{
							global::Loreline.Internal.Hscript.Expr e4 = ( e as global::Loreline.Internal.Hscript.Expr_EField ).e;
							f.__hx_invoke1_o(default(double), e4);
						}
						
						break;
					}
					
					
					case 6:
					{
						string _g6 = ( e as global::Loreline.Internal.Hscript.Expr_EBinop ).op;
						{
							global::Loreline.Internal.Hscript.Expr e11 = ( e as global::Loreline.Internal.Hscript.Expr_EBinop ).e1;
							global::Loreline.Internal.Hscript.Expr e21 = ( e as global::Loreline.Internal.Hscript.Expr_EBinop ).e2;
							{
								f.__hx_invoke1_o(default(double), e11);
								f.__hx_invoke1_o(default(double), e21);
							}
							
						}
						
						break;
					}
					
					
					case 7:
					{
						string _g7 = ( e as global::Loreline.Internal.Hscript.Expr_EUnop ).op;
						bool _g8 = ( e as global::Loreline.Internal.Hscript.Expr_EUnop ).prefix;
						{
							global::Loreline.Internal.Hscript.Expr e5 = ( e as global::Loreline.Internal.Hscript.Expr_EUnop ).e;
							f.__hx_invoke1_o(default(double), e5);
						}
						
						break;
					}
					
					
					case 8:
					{
						global::Loreline.Internal.Hscript.Expr e6 = ( e as global::Loreline.Internal.Hscript.Expr_ECall ).e;
						global::Loreline.Internal.Root.Array<object> args = ( e as global::Loreline.Internal.Hscript.Expr_ECall ).@params;
						{
							f.__hx_invoke1_o(default(double), e6);
							{
								int _g9 = 0;
								while (( _g9 < args.length )) {
									global::Loreline.Internal.Hscript.Expr a = ((global::Loreline.Internal.Hscript.Expr) (args[_g9]) );
									 ++ _g9;
									f.__hx_invoke1_o(default(double), a);
								}
								
							}
							
						}
						
						break;
					}
					
					
					case 9:
					{
						global::Loreline.Internal.Hscript.Expr c = ( e as global::Loreline.Internal.Hscript.Expr_EIf ).cond;
						global::Loreline.Internal.Hscript.Expr e12 = ( e as global::Loreline.Internal.Hscript.Expr_EIf ).e1;
						global::Loreline.Internal.Hscript.Expr e22 = ( e as global::Loreline.Internal.Hscript.Expr_EIf ).e2;
						{
							f.__hx_invoke1_o(default(double), c);
							f.__hx_invoke1_o(default(double), e12);
							if (( e22 != null )) {
								f.__hx_invoke1_o(default(double), e22);
							}
							
						}
						
						break;
					}
					
					
					case 10:
					{
						global::Loreline.Internal.Hscript.Expr c1 = ( e as global::Loreline.Internal.Hscript.Expr_EWhile ).cond;
						global::Loreline.Internal.Hscript.Expr e7 = ( e as global::Loreline.Internal.Hscript.Expr_EWhile ).e;
						{
							f.__hx_invoke1_o(default(double), c1);
							f.__hx_invoke1_o(default(double), e7);
						}
						
						break;
					}
					
					
					case 11:
					{
						string _g10 = ( e as global::Loreline.Internal.Hscript.Expr_EFor ).v;
						{
							global::Loreline.Internal.Hscript.Expr it = ( e as global::Loreline.Internal.Hscript.Expr_EFor ).it;
							global::Loreline.Internal.Hscript.Expr e8 = ( e as global::Loreline.Internal.Hscript.Expr_EFor ).e;
							{
								f.__hx_invoke1_o(default(double), it);
								f.__hx_invoke1_o(default(double), e8);
							}
							
						}
						
						break;
					}
					
					
					case 12:
					case 13:
					{
						break;
					}
					
					
					case 14:
					{
						global::Loreline.Internal.Root.Array<object> _g11 = ( e as global::Loreline.Internal.Hscript.Expr_EFunction ).args;
						string _g12 = ( e as global::Loreline.Internal.Hscript.Expr_EFunction ).name;
						global::Loreline.Internal.Hscript.CType _g13 = ( e as global::Loreline.Internal.Hscript.Expr_EFunction ).ret;
						{
							global::Loreline.Internal.Hscript.Expr e9 = ( e as global::Loreline.Internal.Hscript.Expr_EFunction ).e;
							f.__hx_invoke1_o(default(double), e9);
						}
						
						break;
					}
					
					
					case 15:
					{
						global::Loreline.Internal.Hscript.Expr e10 = ( e as global::Loreline.Internal.Hscript.Expr_EReturn ).e;
						if (( e10 != null )) {
							f.__hx_invoke1_o(default(double), e10);
						}
						
						break;
					}
					
					
					case 16:
					{
						global::Loreline.Internal.Hscript.Expr e13 = ( e as global::Loreline.Internal.Hscript.Expr_EArray ).e;
						global::Loreline.Internal.Hscript.Expr i = ( e as global::Loreline.Internal.Hscript.Expr_EArray ).index;
						{
							f.__hx_invoke1_o(default(double), e13);
							f.__hx_invoke1_o(default(double), i);
						}
						
						break;
					}
					
					
					case 17:
					{
						global::Loreline.Internal.Root.Array<object> el1 = ( e as global::Loreline.Internal.Hscript.Expr_EArrayDecl ).e;
						{
							int _g14 = 0;
							while (( _g14 < el1.length )) {
								global::Loreline.Internal.Hscript.Expr e14 = ((global::Loreline.Internal.Hscript.Expr) (el1[_g14]) );
								 ++ _g14;
								f.__hx_invoke1_o(default(double), e14);
							}
							
						}
						
						break;
					}
					
					
					case 18:
					{
						string _g15 = ( e as global::Loreline.Internal.Hscript.Expr_ENew ).cl;
						{
							global::Loreline.Internal.Root.Array<object> el2 = ( e as global::Loreline.Internal.Hscript.Expr_ENew ).@params;
							{
								int _g16 = 0;
								while (( _g16 < el2.length )) {
									global::Loreline.Internal.Hscript.Expr e15 = ((global::Loreline.Internal.Hscript.Expr) (el2[_g16]) );
									 ++ _g16;
									f.__hx_invoke1_o(default(double), e15);
								}
								
							}
							
						}
						
						break;
					}
					
					
					case 19:
					{
						global::Loreline.Internal.Hscript.Expr e16 = ( e as global::Loreline.Internal.Hscript.Expr_EThrow ).e;
						f.__hx_invoke1_o(default(double), e16);
						break;
					}
					
					
					case 20:
					{
						string _g17 = ( e as global::Loreline.Internal.Hscript.Expr_ETry ).v;
						global::Loreline.Internal.Hscript.CType _g18 = ( e as global::Loreline.Internal.Hscript.Expr_ETry ).t;
						{
							global::Loreline.Internal.Hscript.Expr e17 = ( e as global::Loreline.Internal.Hscript.Expr_ETry ).e;
							global::Loreline.Internal.Hscript.Expr c2 = ( e as global::Loreline.Internal.Hscript.Expr_ETry ).ecatch;
							{
								f.__hx_invoke1_o(default(double), e17);
								f.__hx_invoke1_o(default(double), c2);
							}
							
						}
						
						break;
					}
					
					
					case 21:
					{
						global::Loreline.Internal.Root.Array<object> fl = ( e as global::Loreline.Internal.Hscript.Expr_EObject ).fl;
						{
							int _g19 = 0;
							while (( _g19 < fl.length )) {
								object fi = fl[_g19];
								 ++ _g19;
								f.__hx_invoke1_o(default(double), ((global::Loreline.Internal.Hscript.Expr) (global::Loreline.Internal.Lang.Runtime.getField(fi, "e", 101, true)) ));
							}
							
						}
						
						break;
					}
					
					
					case 22:
					{
						global::Loreline.Internal.Hscript.Expr c3 = ( e as global::Loreline.Internal.Hscript.Expr_ETernary ).cond;
						global::Loreline.Internal.Hscript.Expr e18 = ( e as global::Loreline.Internal.Hscript.Expr_ETernary ).e1;
						global::Loreline.Internal.Hscript.Expr e23 = ( e as global::Loreline.Internal.Hscript.Expr_ETernary ).e2;
						{
							f.__hx_invoke1_o(default(double), c3);
							f.__hx_invoke1_o(default(double), e18);
							f.__hx_invoke1_o(default(double), e23);
						}
						
						break;
					}
					
					
					case 23:
					{
						global::Loreline.Internal.Hscript.Expr e19 = ( e as global::Loreline.Internal.Hscript.Expr_ESwitch ).e;
						global::Loreline.Internal.Root.Array<object> cases = ( e as global::Loreline.Internal.Hscript.Expr_ESwitch ).cases;
						global::Loreline.Internal.Hscript.Expr def = ( e as global::Loreline.Internal.Hscript.Expr_ESwitch ).defaultExpr;
						{
							f.__hx_invoke1_o(default(double), e19);
							{
								int _g20 = 0;
								while (( _g20 < cases.length )) {
									object c4 = cases[_g20];
									 ++ _g20;
									{
										int _g21 = 0;
										global::Loreline.Internal.Root.Array<object> _g22 = ((global::Loreline.Internal.Root.Array<object>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<object>(((global::Loreline.Internal.Root.Array) (global::Loreline.Internal.Lang.Runtime.getField(c4, "values", 1337394146, true)) ))) );
										while (( _g21 < _g22.length )) {
											global::Loreline.Internal.Hscript.Expr v = ((global::Loreline.Internal.Hscript.Expr) (_g22[_g21]) );
											 ++ _g21;
											f.__hx_invoke1_o(default(double), v);
										}
										
									}
									
									f.__hx_invoke1_o(default(double), ((global::Loreline.Internal.Hscript.Expr) (global::Loreline.Internal.Lang.Runtime.getField(c4, "expr", 1126038837, true)) ));
								}
								
							}
							
							if (( def != null )) {
								f.__hx_invoke1_o(default(double), def);
							}
							
						}
						
						break;
					}
					
					
					case 24:
					{
						global::Loreline.Internal.Hscript.Expr c5 = ( e as global::Loreline.Internal.Hscript.Expr_EDoWhile ).cond;
						global::Loreline.Internal.Hscript.Expr e20 = ( e as global::Loreline.Internal.Hscript.Expr_EDoWhile ).e;
						{
							f.__hx_invoke1_o(default(double), c5);
							f.__hx_invoke1_o(default(double), e20);
						}
						
						break;
					}
					
					
					case 25:
					{
						string name = ( e as global::Loreline.Internal.Hscript.Expr_EMeta ).name;
						global::Loreline.Internal.Root.Array<object> args1 = ( e as global::Loreline.Internal.Hscript.Expr_EMeta ).args;
						global::Loreline.Internal.Hscript.Expr e24 = ( e as global::Loreline.Internal.Hscript.Expr_EMeta ).e;
						{
							if (( args1 != null )) {
								int _g23 = 0;
								while (( _g23 < args1.length )) {
									global::Loreline.Internal.Hscript.Expr a1 = ((global::Loreline.Internal.Hscript.Expr) (args1[_g23]) );
									 ++ _g23;
									f.__hx_invoke1_o(default(double), a1);
								}
								
							}
							
							f.__hx_invoke1_o(default(double), e24);
						}
						
						break;
					}
					
					
					case 26:
					{
						global::Loreline.Internal.Hscript.CType _g24 = ( e as global::Loreline.Internal.Hscript.Expr_ECheckType ).t;
						{
							global::Loreline.Internal.Hscript.Expr e25 = ( e as global::Loreline.Internal.Hscript.Expr_ECheckType ).e;
							f.__hx_invoke1_o(default(double), e25);
						}
						
						break;
					}
					
					
				}
				
			}
		}
		
		
		public static global::Loreline.Internal.Hscript.Expr map(global::Loreline.Internal.Hscript.Expr e, global::Loreline.Internal.Lang.Function f) {
			unchecked {
				global::Loreline.Internal.Hscript.Expr edef = null;
				switch (e._hx_index) {
					case 0:
					{
						global::Loreline.Internal.Hscript.Const _g = ( e as global::Loreline.Internal.Hscript.Expr_EConst ).c;
						edef = e;
						break;
					}
					
					
					case 1:
					{
						string _g1 = ( e as global::Loreline.Internal.Hscript.Expr_EIdent ).v;
						edef = e;
						break;
					}
					
					
					case 2:
					{
						string n = ( e as global::Loreline.Internal.Hscript.Expr_EVar ).n;
						global::Loreline.Internal.Hscript.CType t = ( e as global::Loreline.Internal.Hscript.Expr_EVar ).t;
						global::Loreline.Internal.Hscript.Expr e1 = ( e as global::Loreline.Internal.Hscript.Expr_EVar ).e;
						edef = global::Loreline.Internal.Hscript.Expr.EVar(n, t, ( (( e1 != null )) ? (((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e1)) )) : (null) ));
						break;
					}
					
					
					case 3:
					{
						global::Loreline.Internal.Hscript.Expr e2 = ( e as global::Loreline.Internal.Hscript.Expr_EParent ).e;
						edef = global::Loreline.Internal.Hscript.Expr.EParent(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e2)) ));
						break;
					}
					
					
					case 4:
					{
						global::Loreline.Internal.Root.Array<object> el = ( e as global::Loreline.Internal.Hscript.Expr_EBlock ).e;
						global::Loreline.Internal.Root.Array<object> _g2 = new global::Loreline.Internal.Root.Array<object>(new object[]{});
						{
							int _g3 = 0;
							while (( _g3 < el.length )) {
								global::Loreline.Internal.Hscript.Expr e3 = ((global::Loreline.Internal.Hscript.Expr) (el[_g3]) );
								 ++ _g3;
								_g2.push(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e3)) ));
							}
							
						}
						
						edef = global::Loreline.Internal.Hscript.Expr.EBlock(_g2);
						break;
					}
					
					
					case 5:
					{
						global::Loreline.Internal.Hscript.Expr e4 = ( e as global::Loreline.Internal.Hscript.Expr_EField ).e;
						string fi = ( e as global::Loreline.Internal.Hscript.Expr_EField ).f;
						edef = global::Loreline.Internal.Hscript.Expr.EField(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e4)) ), fi);
						break;
					}
					
					
					case 6:
					{
						string op = ( e as global::Loreline.Internal.Hscript.Expr_EBinop ).op;
						global::Loreline.Internal.Hscript.Expr e11 = ( e as global::Loreline.Internal.Hscript.Expr_EBinop ).e1;
						global::Loreline.Internal.Hscript.Expr e21 = ( e as global::Loreline.Internal.Hscript.Expr_EBinop ).e2;
						edef = global::Loreline.Internal.Hscript.Expr.EBinop(op, ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e11)) ), ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e21)) ));
						break;
					}
					
					
					case 7:
					{
						string op1 = ( e as global::Loreline.Internal.Hscript.Expr_EUnop ).op;
						bool pre = ( e as global::Loreline.Internal.Hscript.Expr_EUnop ).prefix;
						global::Loreline.Internal.Hscript.Expr e5 = ( e as global::Loreline.Internal.Hscript.Expr_EUnop ).e;
						edef = global::Loreline.Internal.Hscript.Expr.EUnop(op1, pre, ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e5)) ));
						break;
					}
					
					
					case 8:
					{
						global::Loreline.Internal.Hscript.Expr e6 = ( e as global::Loreline.Internal.Hscript.Expr_ECall ).e;
						global::Loreline.Internal.Root.Array<object> args = ( e as global::Loreline.Internal.Hscript.Expr_ECall ).@params;
						global::Loreline.Internal.Hscript.Expr edef1 = ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e6)) );
						global::Loreline.Internal.Root.Array<object> _g4 = new global::Loreline.Internal.Root.Array<object>(new object[]{});
						{
							int _g5 = 0;
							while (( _g5 < args.length )) {
								global::Loreline.Internal.Hscript.Expr a = ((global::Loreline.Internal.Hscript.Expr) (args[_g5]) );
								 ++ _g5;
								_g4.push(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), a)) ));
							}
							
						}
						
						edef = global::Loreline.Internal.Hscript.Expr.ECall(edef1, _g4);
						break;
					}
					
					
					case 9:
					{
						global::Loreline.Internal.Hscript.Expr c = ( e as global::Loreline.Internal.Hscript.Expr_EIf ).cond;
						global::Loreline.Internal.Hscript.Expr e12 = ( e as global::Loreline.Internal.Hscript.Expr_EIf ).e1;
						global::Loreline.Internal.Hscript.Expr e22 = ( e as global::Loreline.Internal.Hscript.Expr_EIf ).e2;
						edef = global::Loreline.Internal.Hscript.Expr.EIf(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), c)) ), ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e12)) ), ( (( e22 != null )) ? (((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e22)) )) : (null) ));
						break;
					}
					
					
					case 10:
					{
						global::Loreline.Internal.Hscript.Expr c1 = ( e as global::Loreline.Internal.Hscript.Expr_EWhile ).cond;
						global::Loreline.Internal.Hscript.Expr e7 = ( e as global::Loreline.Internal.Hscript.Expr_EWhile ).e;
						edef = global::Loreline.Internal.Hscript.Expr.EWhile(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), c1)) ), ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e7)) ));
						break;
					}
					
					
					case 11:
					{
						string v = ( e as global::Loreline.Internal.Hscript.Expr_EFor ).v;
						global::Loreline.Internal.Hscript.Expr it = ( e as global::Loreline.Internal.Hscript.Expr_EFor ).it;
						global::Loreline.Internal.Hscript.Expr e8 = ( e as global::Loreline.Internal.Hscript.Expr_EFor ).e;
						edef = global::Loreline.Internal.Hscript.Expr.EFor(v, ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), it)) ), ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e8)) ));
						break;
					}
					
					
					case 12:
					case 13:
					{
						edef = e;
						break;
					}
					
					
					case 14:
					{
						global::Loreline.Internal.Root.Array<object> args1 = ( e as global::Loreline.Internal.Hscript.Expr_EFunction ).args;
						global::Loreline.Internal.Hscript.Expr e9 = ( e as global::Loreline.Internal.Hscript.Expr_EFunction ).e;
						string name = ( e as global::Loreline.Internal.Hscript.Expr_EFunction ).name;
						global::Loreline.Internal.Hscript.CType t1 = ( e as global::Loreline.Internal.Hscript.Expr_EFunction ).ret;
						edef = global::Loreline.Internal.Hscript.Expr.EFunction(args1, ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e9)) ), name, t1);
						break;
					}
					
					
					case 15:
					{
						global::Loreline.Internal.Hscript.Expr e10 = ( e as global::Loreline.Internal.Hscript.Expr_EReturn ).e;
						edef = global::Loreline.Internal.Hscript.Expr.EReturn(( (( e10 != null )) ? (((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e10)) )) : (null) ));
						break;
					}
					
					
					case 16:
					{
						global::Loreline.Internal.Hscript.Expr e13 = ( e as global::Loreline.Internal.Hscript.Expr_EArray ).e;
						global::Loreline.Internal.Hscript.Expr i = ( e as global::Loreline.Internal.Hscript.Expr_EArray ).index;
						edef = global::Loreline.Internal.Hscript.Expr.EArray(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e13)) ), ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), i)) ));
						break;
					}
					
					
					case 17:
					{
						global::Loreline.Internal.Root.Array<object> el1 = ( e as global::Loreline.Internal.Hscript.Expr_EArrayDecl ).e;
						global::Loreline.Internal.Root.Array<object> _g6 = new global::Loreline.Internal.Root.Array<object>(new object[]{});
						{
							int _g7 = 0;
							while (( _g7 < el1.length )) {
								global::Loreline.Internal.Hscript.Expr e14 = ((global::Loreline.Internal.Hscript.Expr) (el1[_g7]) );
								 ++ _g7;
								_g6.push(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e14)) ));
							}
							
						}
						
						edef = global::Loreline.Internal.Hscript.Expr.EArrayDecl(_g6);
						break;
					}
					
					
					case 18:
					{
						string cl = ( e as global::Loreline.Internal.Hscript.Expr_ENew ).cl;
						global::Loreline.Internal.Root.Array<object> el2 = ( e as global::Loreline.Internal.Hscript.Expr_ENew ).@params;
						global::Loreline.Internal.Root.Array<object> _g8 = new global::Loreline.Internal.Root.Array<object>(new object[]{});
						{
							int _g9 = 0;
							while (( _g9 < el2.length )) {
								global::Loreline.Internal.Hscript.Expr e15 = ((global::Loreline.Internal.Hscript.Expr) (el2[_g9]) );
								 ++ _g9;
								_g8.push(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e15)) ));
							}
							
						}
						
						edef = global::Loreline.Internal.Hscript.Expr.ENew(cl, _g8);
						break;
					}
					
					
					case 19:
					{
						global::Loreline.Internal.Hscript.Expr e16 = ( e as global::Loreline.Internal.Hscript.Expr_EThrow ).e;
						edef = global::Loreline.Internal.Hscript.Expr.EThrow(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e16)) ));
						break;
					}
					
					
					case 20:
					{
						global::Loreline.Internal.Hscript.Expr e17 = ( e as global::Loreline.Internal.Hscript.Expr_ETry ).e;
						string v1 = ( e as global::Loreline.Internal.Hscript.Expr_ETry ).v;
						global::Loreline.Internal.Hscript.CType t2 = ( e as global::Loreline.Internal.Hscript.Expr_ETry ).t;
						global::Loreline.Internal.Hscript.Expr c2 = ( e as global::Loreline.Internal.Hscript.Expr_ETry ).ecatch;
						edef = global::Loreline.Internal.Hscript.Expr.ETry(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e17)) ), v1, t2, ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), c2)) ));
						break;
					}
					
					
					case 21:
					{
						global::Loreline.Internal.Root.Array<object> fl = ( e as global::Loreline.Internal.Hscript.Expr_EObject ).fl;
						global::Loreline.Internal.Root.Array<object> _g10 = new global::Loreline.Internal.Root.Array<object>(new object[]{});
						{
							int _g11 = 0;
							while (( _g11 < fl.length )) {
								object fi1 = fl[_g11];
								 ++ _g11;
								string fi2 = global::Loreline.Internal.Lang.Runtime.toString(global::Loreline.Internal.Lang.Runtime.getField(fi1, "name", 1224700491, true));
								object __temp_stmt3 = null;
								{
									global::Loreline.Internal.Hscript.Expr __temp_odecl1 = ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), ((global::Loreline.Internal.Hscript.Expr) (global::Loreline.Internal.Lang.Runtime.getField(fi1, "e", 101, true)) ))) );
									__temp_stmt3 = new global::Loreline.Internal.Lang.DynamicObject(new int[]{101, 1224700491}, new object[]{__temp_odecl1, fi2}, new int[]{}, new double[]{});
								}
								
								_g10.push(__temp_stmt3);
							}
							
						}
						
						edef = global::Loreline.Internal.Hscript.Expr.EObject(_g10);
						break;
					}
					
					
					case 22:
					{
						global::Loreline.Internal.Hscript.Expr c3 = ( e as global::Loreline.Internal.Hscript.Expr_ETernary ).cond;
						global::Loreline.Internal.Hscript.Expr e18 = ( e as global::Loreline.Internal.Hscript.Expr_ETernary ).e1;
						global::Loreline.Internal.Hscript.Expr e23 = ( e as global::Loreline.Internal.Hscript.Expr_ETernary ).e2;
						edef = global::Loreline.Internal.Hscript.Expr.ETernary(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), c3)) ), ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e18)) ), ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e23)) ));
						break;
					}
					
					
					case 23:
					{
						global::Loreline.Internal.Hscript.Expr e19 = ( e as global::Loreline.Internal.Hscript.Expr_ESwitch ).e;
						global::Loreline.Internal.Root.Array<object> cases = ( e as global::Loreline.Internal.Hscript.Expr_ESwitch ).cases;
						global::Loreline.Internal.Hscript.Expr def = ( e as global::Loreline.Internal.Hscript.Expr_ESwitch ).defaultExpr;
						global::Loreline.Internal.Hscript.Expr edef2 = ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e19)) );
						global::Loreline.Internal.Root.Array<object> _g12 = new global::Loreline.Internal.Root.Array<object>(new object[]{});
						{
							int _g13 = 0;
							while (( _g13 < cases.length )) {
								object c4 = cases[_g13];
								 ++ _g13;
								global::Loreline.Internal.Root.Array<object> _g14 = new global::Loreline.Internal.Root.Array<object>(new object[]{});
								{
									int _g15 = 0;
									global::Loreline.Internal.Root.Array<object> _g16 = ((global::Loreline.Internal.Root.Array<object>) (global::Loreline.Internal.Root.Array<object>.__hx_cast<object>(((global::Loreline.Internal.Root.Array) (global::Loreline.Internal.Lang.Runtime.getField(c4, "values", 1337394146, true)) ))) );
									while (( _g15 < _g16.length )) {
										global::Loreline.Internal.Hscript.Expr v2 = ((global::Loreline.Internal.Hscript.Expr) (_g16[_g15]) );
										 ++ _g15;
										_g14.push(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), v2)) ));
									}
									
								}
								
								object __temp_stmt4 = null;
								{
									global::Loreline.Internal.Hscript.Expr __temp_odecl2 = ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), ((global::Loreline.Internal.Hscript.Expr) (global::Loreline.Internal.Lang.Runtime.getField(c4, "expr", 1126038837, true)) ))) );
									__temp_stmt4 = new global::Loreline.Internal.Lang.DynamicObject(new int[]{1126038837, 1337394146}, new object[]{__temp_odecl2, _g14}, new int[]{}, new double[]{});
								}
								
								_g12.push(__temp_stmt4);
							}
							
						}
						
						edef = global::Loreline.Internal.Hscript.Expr.ESwitch(edef2, _g12, ( (( def == null )) ? (null) : (((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), def)) )) ));
						break;
					}
					
					
					case 24:
					{
						global::Loreline.Internal.Hscript.Expr c5 = ( e as global::Loreline.Internal.Hscript.Expr_EDoWhile ).cond;
						global::Loreline.Internal.Hscript.Expr e20 = ( e as global::Loreline.Internal.Hscript.Expr_EDoWhile ).e;
						edef = global::Loreline.Internal.Hscript.Expr.EDoWhile(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), c5)) ), ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e20)) ));
						break;
					}
					
					
					case 25:
					{
						string name1 = ( e as global::Loreline.Internal.Hscript.Expr_EMeta ).name;
						global::Loreline.Internal.Root.Array<object> args2 = ( e as global::Loreline.Internal.Hscript.Expr_EMeta ).args;
						global::Loreline.Internal.Hscript.Expr e24 = ( e as global::Loreline.Internal.Hscript.Expr_EMeta ).e;
						global::Loreline.Internal.Root.Array<object> edef3 = null;
						if (( args2 == null )) {
							edef3 = null;
						}
						else {
							global::Loreline.Internal.Root.Array<object> _g17 = new global::Loreline.Internal.Root.Array<object>(new object[]{});
							{
								int _g18 = 0;
								while (( _g18 < args2.length )) {
									global::Loreline.Internal.Hscript.Expr a1 = ((global::Loreline.Internal.Hscript.Expr) (args2[_g18]) );
									 ++ _g18;
									_g17.push(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), a1)) ));
								}
								
							}
							
							edef3 = _g17;
						}
						
						edef = global::Loreline.Internal.Hscript.Expr.EMeta(name1, edef3, ((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e24)) ));
						break;
					}
					
					
					case 26:
					{
						global::Loreline.Internal.Hscript.Expr e25 = ( e as global::Loreline.Internal.Hscript.Expr_ECheckType ).e;
						global::Loreline.Internal.Hscript.CType t3 = ( e as global::Loreline.Internal.Hscript.Expr_ECheckType ).t;
						edef = global::Loreline.Internal.Hscript.Expr.ECheckType(((global::Loreline.Internal.Hscript.Expr) (f.__hx_invoke1_o(default(double), e25)) ), t3);
						break;
					}
					
					
				}
				
				return edef;
			}
		}
		
		
		public static global::Loreline.Internal.Hscript.Expr expr(global::Loreline.Internal.Hscript.Expr e) {
			return e;
		}
		
		
		public static global::Loreline.Internal.Hscript.Expr mk(global::Loreline.Internal.Hscript.Expr e, global::Loreline.Internal.Hscript.Expr p) {
			return e;
		}
		
		
	}
}


