#!/usr/bin/env python3
"""
Generates the character tables of src/loreline/Identifiers.hx.

Run it with a Python whose Unicode database matches UNICODE_VERSION, then
commit the updated file. It replaces what sits between the BEGIN GENERATED
and END GENERATED lines.

- Names start with a character of XID_Start (what str.isidentifier() accepts
  first) and continue with XID_Continue, as in Python, Rust or JavaScript.
- Emoji count as letters: Extended_Pictographic from U+2300 up (the older
  symbols below, such as (c) or (tm), stay text), and the regional indicators
  that make flags. The pieces that build an emoji sequence (joiner, variation
  selectors, skin tones, tag characters) can continue a name.
- Case and script tables serve editor heuristics and warnings only.
"""

import os
import re
import sys
import unicodedata
import urllib.request

UNICODE_VERSION = '16.0.0'
EMOJI_DATA_URL = f'https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/emoji/emoji-data.txt'
TARGET = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'loreline', 'Identifiers.hx')

if unicodedata.unidata_version != UNICODE_VERSION:
    sys.exit(f'This Python has Unicode {unicodedata.unidata_version}, expected {UNICODE_VERSION}')

def ranges_of(pred):
    out = []
    start = None
    for cp in range(0x110000):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out

def extended_pictographic():
    text = urllib.request.urlopen(EMOJI_DATA_URL).read().decode('utf-8')
    result = set()
    for line in text.splitlines():
        line = line.split('#')[0].strip()
        if not line:
            continue
        cps, prop = [part.strip() for part in line.split(';')]
        if prop != 'Extended_Pictographic':
            continue
        if '..' in cps:
            a, b = cps.split('..')
            result.update(range(int(a, 16), int(b, 16) + 1))
        else:
            result.add(int(cps, 16))
    return result

# Pictographic characters that work as punctuation in text, and must end a name
# like any other punctuation mark
not_names = {
    0x3030,  # wavy dash, used in Japanese text
    0x303D,  # part alternation mark, a Japanese punctuation mark
}

pictographic = {cp for cp in extended_pictographic() if cp >= 0x2300 and cp not in not_names}
flags = set(range(0x1F1E6, 0x1F1FF + 1))
pieces = {0x200D, 0xFE0E, 0xFE0F} | set(range(0x1F3FB, 0x1F3FF + 1)) | set(range(0xE0020, 0xE007F + 1))

def is_start(cp):
    return chr(cp).isidentifier() or cp in pictographic or cp in flags

def is_part(cp):
    return is_start(cp) or ('a' + chr(cp)).isidentifier() or cp in pieces

def script_of(cp):
    if not unicodedata.category(chr(cp)).startswith('L'):
        return None
    name = unicodedata.name(chr(cp), '')
    for script in ('LATIN', 'GREEK', 'CYRILLIC'):
        if script + ' ' in name:
            return script
    return None

def array(name, rs, doc):
    # Written as text, hexadecimal code points separated by spaces, which a
    # macro turns into the array at compile time (see IdentifierTables)
    lines = [f'    /** {doc} */', f'    static final {name}:Array<Int> = #if macro [] #else IdentifierTables.decode(']
    flat = [f'{v:X}' for r in rs for v in r]
    for i in range(0, len(flat), 16):
        last = i + 16 >= len(flat)
        lines.append('        "' + ' '.join(flat[i:i + 16]) + ('"' if last else ' " +'))
    lines.append('    ) #end;')
    return '\n'.join(lines)

blocks = [
    f'    // Unicode {UNICODE_VERSION}, generated by tools/identifier-tables.py. The tables are',
    '    // empty in the macro context, where nothing reads them and the macro that',
    '    // builds them can\'t run.',
    '',
    array('START', ranges_of(is_start), 'Characters that can start a name, as pairs of first and last code points'),
    '',
    array('PART', ranges_of(is_part), 'Characters that can continue a name'),
    '',
    array('EMOJI', ranges_of(lambda cp: cp in pictographic or cp in flags), 'Emoji that can start a name'),
    '',
    array('LOWER', ranges_of(lambda cp: unicodedata.category(chr(cp)) == 'Ll'), 'Lower case letters'),
    '',
    array('UPPER', ranges_of(lambda cp: unicodedata.category(chr(cp)) in ('Lu', 'Lt')), 'Upper case and title case letters'),
    '',
    array('LATIN', ranges_of(lambda cp: script_of(cp) == 'LATIN'), 'Latin letters'),
    '',
    array('GREEK', ranges_of(lambda cp: script_of(cp) == 'GREEK'), 'Greek letters'),
    '',
    array('CYRILLIC', ranges_of(lambda cp: script_of(cp) == 'CYRILLIC'), 'Cyrillic letters'),
]

with open(TARGET, encoding='utf-8') as f:
    source = f.read()
pattern = re.compile(r'(    // BEGIN GENERATED\n)(?:.*?\n)?(    // END GENERATED)', re.S)
if not pattern.search(source):
    sys.exit('Missing BEGIN GENERATED / END GENERATED lines in ' + TARGET)
source = pattern.sub(lambda m: m.group(1) + '\n'.join(blocks) + '\n' + m.group(2), source)
with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(source)
print('Updated', os.path.normpath(TARGET))
