// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Lang {
	public class StringExt {
		
		public StringExt() {
		}
		
		
		public static readonly global::System.String empty = new global::System.String(((char) (0) ), ((int) (0) ));
		
		public static global::System.String charAt(global::System.String me, int index) {
			unchecked {
				if (( ((uint) (index) ) >= me.Length )) {
					return global::Loreline.Internal.Lang.StringExt.empty;
				}
				else {
					return new global::System.String(((char) (me[index]) ), ((int) (1) ));
				}
				
			}
		}
		
		
		public static object charCodeAt(global::System.String me, int index) {
			if (( ((uint) (index) ) >= me.Length )) {
				return null;
			}
			else {
				return ((int) (me[index]) );
			}
			
		}
		
		
		public static int indexOf(global::System.String me, string str) {
			return global::Loreline.Internal.Lang.StringExt.indexOf(me, str, default(object));
		}
		
		
		public static int indexOf(global::System.String me, string str, object startIndex) {
			unchecked {
				int sIndex = ( (( startIndex != default(object) )) ? (((int) (global::Loreline.Internal.Lang.Runtime.toInt(startIndex)) )) : (0) );
				if (( str == "" )) {
					if (( sIndex < 0 )) {
						sIndex = ( me.Length + sIndex );
						if (( sIndex < 0 )) {
							sIndex = 0;
						}
						
					}
					
					if (( sIndex > me.Length )) {
						return me.Length;
					}
					else {
						return sIndex;
					}
					
				}
				
				if (( sIndex >= me.Length )) {
					return -1;
				}
				
				return me.IndexOf(((string) (str) ), ((int) (sIndex) ), ((global::System.StringComparison) (global::System.StringComparison.Ordinal) ));
			}
		}
		
		
		public static int lastIndexOf(global::System.String me, global::System.String str) {
			return global::Loreline.Internal.Lang.StringExt.lastIndexOf(me, str, default(object));
		}
		
		
		public static int lastIndexOf(global::System.String me, global::System.String str, object startIndex) {
			unchecked {
				int sIndex = ( (( startIndex == default(object) )) ? (( me.Length - 1 )) : (((int) (global::Loreline.Internal.Lang.Runtime.toInt(startIndex)) )) );
				if (( sIndex >= me.Length )) {
					sIndex = ( me.Length - 1 );
				}
				else if (( sIndex < 0 )) {
					return -1;
				}
				
				if (( str.Length == 0 )) {
					if (( ( startIndex == default(object) ) || ( ((int) (global::Loreline.Internal.Lang.Runtime.toInt(startIndex)) ) > me.Length ) )) {
						return me.Length;
					}
					else {
						return ((int) (global::Loreline.Internal.Lang.Runtime.toInt(startIndex)) );
					}
					
				}
				
				if (( startIndex != default(object) )) {
					int d = ( ( me.Length - sIndex ) - str.Length );
					if (( d < 0 )) {
						sIndex += d;
					}
					
					int i = ( sIndex + 1 );
					while (( i-- > 0 )) {
						bool found = true;
						{
							int _g = 0;
							int _g1 = str.Length;
							while (( _g < _g1 )) {
								int j = _g++;
								if (( me[( i + j )] != str[j] )) {
									found = false;
									break;
								}
								
							}
							
						}
						
						if (found) {
							return i;
						}
						
					}
					
					return -1;
				}
				else {
					return me.LastIndexOf(((string) (str) ), ((int) (sIndex) ), ((global::System.StringComparison) (global::System.StringComparison.Ordinal) ));
				}
				
			}
		}
		
		
		public static global::Loreline.Internal.Root.Array split(global::System.String me, global::System.String delimiter) {
			unchecked {
				string[] native = null;
				if (( delimiter.Length == 0 )) {
					int len = me.Length;
					native = new string[len];
					{
						int _g = 0;
						int _g1 = len;
						while (( _g < _g1 )) {
							int i = _g++;
							native[i] = new global::System.String(((char) (me[i]) ), ((int) (1) ));
						}
						
					}
					
				}
				else {
					string[] str = new string[1];
					str[0] = global::Loreline.Internal.Lang.Runtime.toString(delimiter);
					native = me.Split(((string[]) (str) ), ((global::System.StringSplitOptions) (global::System.StringSplitOptions.None) ));
				}
				
				object[] ret = new object[( native as global::System.Array ).Length];
				{
					int _g2 = 0;
					int _g3 = ( native as global::System.Array ).Length;
					while (( _g2 < _g3 )) {
						int i1 = _g2++;
						ret[i1] = ((string) (native[i1]) );
					}
					
				}
				
				object[] dyn = ret;
				return new global::Loreline.Internal.Root.Array(((object[]) (dyn) ));
			}
		}
		
		
		public static string substr(global::System.String me, int pos) {
			return global::Loreline.Internal.Lang.StringExt.substr(me, pos, default(object));
		}
		
		
		public static string substr(global::System.String me, int pos, object len) {
			int meLen = me.Length;
			int targetLen = meLen;
			if (( len != default(object) )) {
				targetLen = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(len)) );
				if (( ( targetLen == 0 ) || ( ( pos != 0 ) && ( targetLen < 0 ) ) )) {
					return "";
				}
				
			}
			
			if (( pos < 0 )) {
				pos = ( meLen + pos );
				if (( pos < 0 )) {
					pos = 0;
				}
				
			}
			else if (( targetLen < 0 )) {
				targetLen = ( ( meLen + targetLen ) - pos );
			}
			
			if (( ( pos + targetLen ) > meLen )) {
				targetLen = ( meLen - pos );
			}
			
			if (( ( pos < 0 ) || ( targetLen <= 0 ) )) {
				return "";
			}
			
			return me.Substring(((int) (pos) ), ((int) (targetLen) ));
		}
		
		
		public static string substring(global::System.String me, int startIndex) {
			return global::Loreline.Internal.Lang.StringExt.substring(me, startIndex, default(object));
		}
		
		
		public static string substring(global::System.String me, int startIndex, object endIndex) {
			int len = me.Length;
			int endIdx = default(int);
			if (( endIndex == default(object) )) {
				endIdx = len;
			}
			else {
				endIdx = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(endIndex)) );
				if (( endIdx < 0 )) {
					endIdx = 0;
				}
				else if (( endIdx > len )) {
					endIdx = len;
				}
				
			}
			
			if (( startIndex < 0 )) {
				startIndex = 0;
			}
			else if (( startIndex > len )) {
				startIndex = len;
			}
			
			if (( startIndex > endIdx )) {
				int tmp = startIndex;
				startIndex = endIdx;
				endIdx = tmp;
			}
			
			return me.Substring(((int) (startIndex) ), ((int) (( endIdx - startIndex )) ));
		}
		
		
		public static global::System.String toString(global::System.String me) {
			return me;
		}
		
		
		public static string toLowerCase(global::System.String me) {
			return me.ToLowerInvariant();
		}
		
		
		public static string toUpperCase(global::System.String me) {
			return me.ToUpperInvariant();
		}
		
		
		public static global::System.String toNativeString(global::System.String me) {
			return me;
		}
		
		
		public static string fromCharCode(int code) {
			return global::System.Char.ConvertFromUtf32(((int) (code) ));
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Lang {
	public class StringRefl {
		
		static StringRefl() {
			global::Loreline.Internal.Lang.StringRefl.fields = new global::Loreline.Internal.Root.Array(new object[]{"length", "toUpperCase", "toLowerCase", "charAt", "charCodeAt", "indexOf", "lastIndexOf", "split", "substr", "substring"});
		}
		
		
		public StringRefl() {
		}
		
		
		public static global::Loreline.Internal.Root.Array fields;
		
		public static object handleGetField(string str, string f, bool throwErrors) {
			switch (f) {
				case "length":
				{
					return str.Length;
				}
				
				
				case "charAt":
				case "charCodeAt":
				case "indexOf":
				case "lastIndexOf":
				case "split":
				case "substr":
				case "substring":
				case "toLowerCase":
				case "toUpperCase":
				{
					return new global::Loreline.Internal.Lang.Closure(str, f, 0);
				}
				
				
				default:
				{
					if (throwErrors) {
						throw ((global::System.Exception) (global::Loreline.Internal.Exception.thrown(global::Loreline.Internal.Lang.Runtime.concat(global::Loreline.Internal.Lang.Runtime.concat("Field not found: \'", f), "\' in String"))) );
					}
					else {
						return null;
					}
					
				}
				
			}
			
		}
		
		
		public static object handleCallField(global::System.String str, string f, object[] args) {
			unchecked {
				object[] _args = null;
				if (( args == null )) {
					_args = new global::System.String[]{((global::System.String) (str) )};
				}
				else {
					_args = new object[( ( args as global::System.Array ).Length + 1 )];
					{
						int _g = 0;
						int _g1 = ( args as global::System.Array ).Length;
						while (( _g < _g1 )) {
							int i = _g++;
							_args[( i + 1 )] = ((object) (args[i]) );
						}
						
					}
					
					_args[0] = str;
				}
				
				return global::Loreline.Internal.Lang.Runtime.slowCallField(typeof(global::Loreline.Internal.Lang.StringExt), f, _args);
			}
		}
		
		
	}
}


