// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Ds {
	public class List : global::Loreline.Internal.Lang.HxObject {
		
		public List(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public List() {
			global::Loreline.Internal.Ds.List.__hx_ctor_haxe_ds_List(((global::Loreline.Internal.Ds.List) (this) ));
		}
		
		
		protected static void __hx_ctor_haxe_ds_List(global::Loreline.Internal.Ds.List __hx_this) {
			__hx_this.length = 0;
		}
		
		
		public global::Loreline.Internal.Ds._List.ListNode h;
		
		public global::Loreline.Internal.Ds._List.ListNode q;
		
		public int length;
		
		public virtual void @add(object item) {
			global::Loreline.Internal.Ds._List.ListNode next = null;
			global::Loreline.Internal.Ds._List.ListNode x = new global::Loreline.Internal.Ds._List.ListNode(((object) (item) ), ((global::Loreline.Internal.Ds._List.ListNode) (next) ));
			if (( this.h == null )) {
				this.h = x;
			}
			else {
				this.q.next = x;
			}
			
			this.q = x;
			this.length++;
		}
		
		
		public virtual void push(object item) {
			global::Loreline.Internal.Ds._List.ListNode x = new global::Loreline.Internal.Ds._List.ListNode(((object) (item) ), ((global::Loreline.Internal.Ds._List.ListNode) (this.h) ));
			this.h = x;
			if (( this.q == null )) {
				this.q = x;
			}
			
			this.length++;
		}
		
		
		public virtual object pop() {
			if (( this.h == null )) {
				return null;
			}
			
			object x = this.h.item;
			this.h = this.h.next;
			if (( this.h == null )) {
				this.q = null;
			}
			
			this.length--;
			return x;
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 520590566:
					{
						this.length = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 520590566:
					{
						this.length = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 113:
					{
						this.q = ((global::Loreline.Internal.Ds._List.ListNode) (@value) );
						return @value;
					}
					
					
					case 104:
					{
						this.h = ((global::Loreline.Internal.Ds._List.ListNode) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 5594513:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "pop", 5594513)) );
					}
					
					
					case 1247875546:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "push", 1247875546)) );
					}
					
					
					case 4846113:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "add", 4846113)) );
					}
					
					
					case 520590566:
					{
						return this.length;
					}
					
					
					case 113:
					{
						return this.q;
					}
					
					
					case 104:
					{
						return this.h;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 520590566:
					{
						return ((double) (this.length) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 5594513:
					{
						return this.pop();
					}
					
					
					case 1247875546:
					{
						this.push(((object) (dynargs[0]) ));
						break;
					}
					
					
					case 4846113:
					{
						this.@add(((object) (dynargs[0]) ));
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array baseArr) {
			baseArr.push("length");
			baseArr.push("q");
			baseArr.push("h");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Ds._List {
	public class ListNode : global::Loreline.Internal.Lang.HxObject {
		
		public ListNode(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public ListNode(object item, global::Loreline.Internal.Ds._List.ListNode next) {
			global::Loreline.Internal.Ds._List.ListNode.__hx_ctor_haxe_ds__List_ListNode(((global::Loreline.Internal.Ds._List.ListNode) (this) ), ((object) (item) ), ((global::Loreline.Internal.Ds._List.ListNode) (next) ));
		}
		
		
		protected static void __hx_ctor_haxe_ds__List_ListNode(global::Loreline.Internal.Ds._List.ListNode __hx_this, object item, global::Loreline.Internal.Ds._List.ListNode next) {
			__hx_this.item = item;
			__hx_this.next = next;
		}
		
		
		public object item;
		
		public global::Loreline.Internal.Ds._List.ListNode next;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1170195731:
					{
						this.item = ((object) (@value) );
						return ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(((object) (@value) ))) );
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1224901875:
					{
						this.next = ((global::Loreline.Internal.Ds._List.ListNode) (@value) );
						return @value;
					}
					
					
					case 1170195731:
					{
						this.item = ((object) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1224901875:
					{
						return this.next;
					}
					
					
					case 1170195731:
					{
						return this.item;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1170195731:
					{
						return ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(((object) (this.item) ))) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array baseArr) {
			baseArr.push("next");
			baseArr.push("item");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


