// Generated by Haxe 4.3.6
using global::Loreline.Internal.Root;

#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Ds {
	public class List<T> : global::Loreline.Internal.Lang.HxObject, global::Loreline.Internal.Ds.List {
		
		public List(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public List() {
			global::Loreline.Internal.Ds.List<object>.__hx_ctor_haxe_ds_List<T>(((global::Loreline.Internal.Ds.List<T>) (this) ));
		}
		
		
		protected static void __hx_ctor_haxe_ds_List<T_c>(global::Loreline.Internal.Ds.List<T_c> __hx_this) {
			__hx_this.length = 0;
		}
		
		
		public static object __hx_cast<T_c_c>(global::Loreline.Internal.Ds.List me) {
			return ( (( me != null )) ? (me.haxe_ds_List_cast<T_c_c>()) : default(object) );
		}
		
		
		public virtual object haxe_ds_List_cast<T_c>() {
			if (global::Loreline.Internal.Lang.Runtime.eq(typeof(T), typeof(T_c))) {
				return this;
			}
			
			global::Loreline.Internal.Ds.List<T_c> new_me = new global::Loreline.Internal.Ds.List<T_c>(global::Loreline.Internal.Lang.EmptyObject.EMPTY);
			global::Loreline.Internal.Root.Array<string> fields = global::Loreline.Internal.Root.Reflect.fields(this);
			int i = 0;
			while (( i < fields.length )) {
				string field = fields[i++];
				global::Loreline.Internal.Root.Reflect.setField(new_me, field, global::Loreline.Internal.Root.Reflect.field(this, field));
			}
			
			return new_me;
		}
		
		
		public global::Loreline.Internal.Ds._List.ListNode<T> h;
		
		public global::Loreline.Internal.Ds._List.ListNode<T> q;
		
		public int length;
		
		public virtual void @add(T item) {
			global::Loreline.Internal.Ds._List.ListNode<T> next = null;
			global::Loreline.Internal.Ds._List.ListNode<T> x = new global::Loreline.Internal.Ds._List.ListNode<T>(global::Loreline.Internal.Lang.Runtime.genericCast<T>(item), ((global::Loreline.Internal.Ds._List.ListNode<T>) (next) ));
			if (( this.h == null )) {
				this.h = x;
			}
			else {
				this.q.next = x;
			}
			
			this.q = x;
			this.length++;
		}
		
		
		public virtual void push(T item) {
			global::Loreline.Internal.Ds._List.ListNode<T> x = new global::Loreline.Internal.Ds._List.ListNode<T>(global::Loreline.Internal.Lang.Runtime.genericCast<T>(item), ((global::Loreline.Internal.Ds._List.ListNode<T>) (this.h) ));
			this.h = x;
			if (( this.q == null )) {
				this.q = x;
			}
			
			this.length++;
		}
		
		
		public virtual global::Loreline.Internal.Lang.Null<T> pop() {
			if (( this.h == null )) {
				return default(global::Loreline.Internal.Lang.Null<T>);
			}
			
			T x = this.h.item;
			this.h = this.h.next;
			if (( this.h == null )) {
				this.q = null;
			}
			
			this.length--;
			return new global::Loreline.Internal.Lang.Null<T>(x, true);
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 520590566:
					{
						this.length = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 520590566:
					{
						this.length = ((int) (global::Loreline.Internal.Lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 113:
					{
						this.q = ((global::Loreline.Internal.Ds._List.ListNode<T>) (global::Loreline.Internal.Ds._List.ListNode<object>.__hx_cast<T>(((global::Loreline.Internal.Ds._List.ListNode) (@value) ))) );
						return @value;
					}
					
					
					case 104:
					{
						this.h = ((global::Loreline.Internal.Ds._List.ListNode<T>) (global::Loreline.Internal.Ds._List.ListNode<object>.__hx_cast<T>(((global::Loreline.Internal.Ds._List.ListNode) (@value) ))) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 5594513:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "pop", 5594513)) );
					}
					
					
					case 1247875546:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "push", 1247875546)) );
					}
					
					
					case 4846113:
					{
						return ((global::Loreline.Internal.Lang.Function) (new global::Loreline.Internal.Lang.Closure(this, "add", 4846113)) );
					}
					
					
					case 520590566:
					{
						return this.length;
					}
					
					
					case 113:
					{
						return this.q;
					}
					
					
					case 104:
					{
						return this.h;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 520590566:
					{
						return ((double) (this.length) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 5594513:
					{
						return (this.pop()).toDynamic();
					}
					
					
					case 1247875546:
					{
						this.push(global::Loreline.Internal.Lang.Runtime.genericCast<T>(dynargs[0]));
						break;
					}
					
					
					case 4846113:
					{
						this.@add(global::Loreline.Internal.Lang.Runtime.genericCast<T>(dynargs[0]));
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("length");
			baseArr.push("q");
			baseArr.push("h");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Ds {
	[global::Loreline.Internal.Lang.GenericInterface(typeof(global::Loreline.Internal.Ds.List<object>))]
	public interface List : global::Loreline.Internal.Lang.IHxObject, global::Loreline.Internal.Lang.IGenericObject {
		
		object haxe_ds_List_cast<T_c>();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Ds._List {
	public class ListNode<T> : global::Loreline.Internal.Lang.HxObject, global::Loreline.Internal.Ds._List.ListNode {
		
		public ListNode(global::Loreline.Internal.Lang.EmptyObject empty) {
		}
		
		
		public ListNode(T item, global::Loreline.Internal.Ds._List.ListNode<T> next) {
			global::Loreline.Internal.Ds._List.ListNode<object>.__hx_ctor_haxe_ds__List_ListNode<T>(((global::Loreline.Internal.Ds._List.ListNode<T>) (this) ), global::Loreline.Internal.Lang.Runtime.genericCast<T>(item), ((global::Loreline.Internal.Ds._List.ListNode<T>) (next) ));
		}
		
		
		protected static void __hx_ctor_haxe_ds__List_ListNode<T_c>(global::Loreline.Internal.Ds._List.ListNode<T_c> __hx_this, T_c item, global::Loreline.Internal.Ds._List.ListNode<T_c> next) {
			__hx_this.item = item;
			__hx_this.next = next;
		}
		
		
		public static object __hx_cast<T_c_c>(global::Loreline.Internal.Ds._List.ListNode me) {
			return ( (( me != null )) ? (me.haxe_ds__List_ListNode_cast<T_c_c>()) : default(object) );
		}
		
		
		public virtual object haxe_ds__List_ListNode_cast<T_c>() {
			if (global::Loreline.Internal.Lang.Runtime.eq(typeof(T), typeof(T_c))) {
				return this;
			}
			
			global::Loreline.Internal.Ds._List.ListNode<T_c> new_me = new global::Loreline.Internal.Ds._List.ListNode<T_c>(global::Loreline.Internal.Lang.EmptyObject.EMPTY);
			global::Loreline.Internal.Root.Array<string> fields = global::Loreline.Internal.Root.Reflect.fields(this);
			int i = 0;
			while (( i < fields.length )) {
				string field = fields[i++];
				global::Loreline.Internal.Root.Reflect.setField(new_me, field, global::Loreline.Internal.Root.Reflect.field(this, field));
			}
			
			return new_me;
		}
		
		
		public T item;
		
		public global::Loreline.Internal.Ds._List.ListNode<T> next;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1170195731:
					{
						this.item = global::Loreline.Internal.Lang.Runtime.genericCast<T>(((object) (@value) ));
						return ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(((object) (@value) ))) );
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1224901875:
					{
						this.next = ((global::Loreline.Internal.Ds._List.ListNode<T>) (global::Loreline.Internal.Ds._List.ListNode<object>.__hx_cast<T>(((global::Loreline.Internal.Ds._List.ListNode) (@value) ))) );
						return @value;
					}
					
					
					case 1170195731:
					{
						this.item = global::Loreline.Internal.Lang.Runtime.genericCast<T>(@value);
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1224901875:
					{
						return this.next;
					}
					
					
					case 1170195731:
					{
						return this.item;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1170195731:
					{
						return ((double) (global::Loreline.Internal.Lang.Runtime.toDouble(((object) (this.item) ))) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Loreline.Internal.Root.Array<string> baseArr) {
			baseArr.push("next");
			baseArr.push("item");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162, IL2026, IL2070, IL2072, IL2060, CS0108
namespace Loreline.Internal.Ds._List {
	[global::Loreline.Internal.Lang.GenericInterface(typeof(global::Loreline.Internal.Ds._List.ListNode<object>))]
	public interface ListNode : global::Loreline.Internal.Lang.IHxObject, global::Loreline.Internal.Lang.IGenericObject {
		
		object haxe_ds__List_ListNode_cast<T_c>();
		
	}
}


